import { prisma } from "../ingestion/engine/prisma";
import { builder } from "../ingestion/engine/builder";

/**
 * Seeds the Panini Adrenalyn XL World Cup 2026 trading card set.
 * Complete 648-card checklist with all national teams, Golden Baller, Fan Favourites,
 * ICONs, Team Crests, and special subsets.
 */
const SET_ID = "panini-adrenalyn-wc-2026";
const SET_NAME = "Adrenalyn XL World Cup 2026";

interface CardRow {
  number: string;
  name: string;
  team: string;
  type?: string;
  persons?: string[];
}

const ALL_CARDS: CardRow[] = [
  // Golden Baller (1-9)
  { number: "1", name: "Lionel Messi GB", team: "Argentina", type: "Golden Baller", persons: ["Lionel Messi"] },
  { number: "2", name: "Vinicius Junior GB", team: "Brazil", type: "Golden Baller", persons: ["Vinicius Junior"] },
  { number: "3", name: "Mohamed Salah GB", team: "Egypt", type: "Golden Baller", persons: ["Mohamed Salah"] },
  { number: "4", name: "Harry Kane GB", team: "England", type: "Golden Baller", persons: ["Harry Kane"] },
  { number: "5", name: "Kylian Mbappé GB", team: "France", type: "Golden Baller", persons: ["Kylian Mbappé"] },
  { number: "6", name: "Son Heung-Min GB", team: "Korea Republic", type: "Golden Baller", persons: ["Son Heung-Min"] },
  { number: "7", name: "Erling Haaland GB", team: "Norway", type: "Golden Baller", persons: ["Erling Haaland"] },
  { number: "8", name: "Cristiano Ronaldo GB", team: "Portugal", type: "Golden Baller", persons: ["Cristiano Ronaldo"] },
  { number: "9", name: "Lamine Yamal GB", team: "Spain", type: "Golden Baller", persons: ["Lamine Yamal"] },

  // Algeria (10-21)
  { number: "10", name: "Rayan Aït-Nouri FF", team: "Algeria", type: "Fan Favourite", persons: ["Rayan Aït-Nouri"] },
  { number: "11", name: "Team Crest TC", team: "Algeria", type: "Team Crest" },
  { number: "12", name: "Riyad Mahrez ICON", team: "Algeria", type: "Icon", persons: ["Riyad Mahrez"] },
  { number: "13", name: "Alexis Guendouz", team: "Algeria", persons: ["Alexis Guendouz"] },
  { number: "14", name: "Ramy Bensebaini", team: "Algeria", persons: ["Ramy Bensebaini"] },
  { number: "15", name: "Youcef Atal", team: "Algeria", persons: ["Youcef Atal"] },
  { number: "16", name: "Aissa Mandi", team: "Algeria", persons: ["Aissa Mandi"] },
  { number: "17", name: "Nabil Bentaleb", team: "Algeria", persons: ["Nabil Bentaleb"] },
  { number: "18", name: "Said Benrahma", team: "Algeria", persons: ["Said Benrahma"] },
  { number: "19", name: "Amine Gouiri", team: "Algeria", persons: ["Amine Gouiri"] },
  { number: "20", name: "Mohamed Amoura", team: "Algeria", persons: ["Mohamed Amoura"] },
  { number: "21", name: "Baghdad Bounedjah", team: "Algeria", persons: ["Baghdad Bounedjah"] },

  // Argentina (22-33)
  { number: "22", name: "Julian Alvarez FF", team: "Argentina", type: "Fan Favourite", persons: ["Julian Alvarez"] },
  { number: "23", name: "Team Crest TC", team: "Argentina", type: "Team Crest" },
  { number: "24", name: "Lionel Messi ICON", team: "Argentina", type: "Icon", persons: ["Lionel Messi"] },
  { number: "25", name: "Emiliano Martinez", team: "Argentina", persons: ["Emiliano Martinez"] },
  { number: "26", name: "Nahuel Molina", team: "Argentina", persons: ["Nahuel Molina"] },
  { number: "27", name: "Cristian Romero", team: "Argentina", persons: ["Cristian Romero"] },
  { number: "28", name: "Nicolas Otamendi", team: "Argentina", persons: ["Nicolas Otamendi"] },
  { number: "29", name: "Enzo Fernandez", team: "Argentina", persons: ["Enzo Fernandez"] },
  { number: "30", name: "Alexis Mac Allister", team: "Argentina", persons: ["Alexis Mac Allister"] },
  { number: "31", name: "Rodrigo De Paul", team: "Argentina", persons: ["Rodrigo De Paul"] },
  { number: "32", name: "Giuliano Simeone", team: "Argentina", persons: ["Giuliano Simeone"] },
  { number: "33", name: "Lautaro Martinez", team: "Argentina", persons: ["Lautaro Martinez"] },

  // Australia (34-45)
  { number: "34", name: "Harry Souttar FF", team: "Australia", type: "Fan Favourite", persons: ["Harry Souttar"] },
  { number: "35", name: "Team Crest TC", team: "Australia", type: "Team Crest" },
  { number: "36", name: "Mathew Ryan ICON", team: "Australia", type: "Icon", persons: ["Mathew Ryan"] },
  { number: "37", name: "Alessandro Circati", team: "Australia", persons: ["Alessandro Circati"] },
  { number: "38", name: "Jordan Bos", team: "Australia", persons: ["Jordan Bos"] },
  { number: "39", name: "Lewis Miller", team: "Australia", persons: ["Lewis Miller"] },
  { number: "40", name: "Milos Degenek", team: "Australia", persons: ["Milos Degenek"] },
  { number: "41", name: "Jackson Irvine", team: "Australia", persons: ["Jackson Irvine"] },
  { number: "42", name: "Riley McGree", team: "Australia", persons: ["Riley McGree"] },
  { number: "43", name: "Aiden O'Neill", team: "Australia", persons: ["Aiden O'Neill"] },
  { number: "44", name: "Connor Metcalfe", team: "Australia", persons: ["Connor Metcalfe"] },
  { number: "45", name: "Craig Goodwin", team: "Australia", persons: ["Craig Goodwin"] },

  // Austria (46-57)
  { number: "46", name: "Marko Arnautovic FF", team: "Austria", type: "Fan Favourite", persons: ["Marko Arnautovic"] },
  { number: "47", name: "Team Crest TC", team: "Austria", type: "Team Crest" },
  { number: "48", name: "David Alaba ICON", team: "Austria", type: "Icon", persons: ["David Alaba"] },
  { number: "49", name: "Alexander Schlager", team: "Austria", persons: ["Alexander Schlager"] },
  { number: "50", name: "Kevin Danso", team: "Austria", persons: ["Kevin Danso"] },
  { number: "51", name: "Philipp Lienhart", team: "Austria", persons: ["Philipp Lienhart"] },
  { number: "52", name: "Konrad Laimer", team: "Austria", persons: ["Konrad Laimer"] },
  { number: "53", name: "Nicolas Seiwald", team: "Austria", persons: ["Nicolas Seiwald"] },
  { number: "54", name: "Marcel Sabitzer", team: "Austria", persons: ["Marcel Sabitzer"] },
  { number: "55", name: "Florian Grillitsch", team: "Austria", persons: ["Florian Grillitsch"] },
  { number: "56", name: "Christoph Baumgartner", team: "Austria", persons: ["Christoph Baumgartner"] },
  { number: "57", name: "Michael Gregoritsch", team: "Austria", persons: ["Michael Gregoritsch"] },

  // Belgium (58-69)
  { number: "58", name: "Youri Tielemans FF", team: "Belgium", type: "Fan Favourite", persons: ["Youri Tielemans"] },
  { number: "59", name: "Team Crest TC", team: "Belgium", type: "Team Crest" },
  { number: "60", name: "Kevin De Bruyne ICON", team: "Belgium", type: "Icon", persons: ["Kevin De Bruyne"] },
  { number: "61", name: "Thibaut Courtois", team: "Belgium", persons: ["Thibaut Courtois"] },
  { number: "62", name: "Arthur Theate", team: "Belgium", persons: ["Arthur Theate"] },
  { number: "63", name: "Timothy Castagne", team: "Belgium", persons: ["Timothy Castagne"] },
  { number: "64", name: "Maxim De Cuyper", team: "Belgium", persons: ["Maxim De Cuyper"] },
  { number: "65", name: "Amadou Onana", team: "Belgium", persons: ["Amadou Onana"] },
  { number: "66", name: "Jeremy Doku", team: "Belgium", persons: ["Jeremy Doku"] },
  { number: "67", name: "Charles De Ketelaere", team: "Belgium", persons: ["Charles De Ketelaere"] },
  { number: "68", name: "Leandro Trossard", team: "Belgium", persons: ["Leandro Trossard"] },
  { number: "69", name: "Romelu Lukaku", team: "Belgium", persons: ["Romelu Lukaku"] },

  // Brazil (70-81)
  { number: "70", name: "Marquinhos FF", team: "Brazil", type: "Fan Favourite", persons: ["Marquinhos"] },
  { number: "71", name: "Team Crest TC", team: "Brazil", type: "Team Crest" },
  { number: "72", name: "Vinicius Junior ICON", team: "Brazil", type: "Icon", persons: ["Vinicius Junior"] },
  { number: "73", name: "Alisson", team: "Brazil", persons: ["Alisson"] },
  { number: "74", name: "Danilo", team: "Brazil", persons: ["Danilo"] },
  { number: "75", name: "Eder Militao", team: "Brazil", persons: ["Eder Militao"] },
  { number: "76", name: "Gabriel Magalhaes", team: "Brazil", persons: ["Gabriel Magalhaes"] },
  { number: "77", name: "Casemiro", team: "Brazil", persons: ["Casemiro"] },
  { number: "78", name: "Bruno Guimaraes", team: "Brazil", persons: ["Bruno Guimaraes"] },
  { number: "79", name: "Rodrygo", team: "Brazil", persons: ["Rodrygo"] },
  { number: "80", name: "Matheus Cunha", team: "Brazil", persons: ["Matheus Cunha"] },
  { number: "81", name: "Raphinha", team: "Brazil", persons: ["Raphinha"] },

  // Canada (82-93)
  { number: "82", name: "Jonathan David FF", team: "Canada", type: "Fan Favourite", persons: ["Jonathan David"] },
  { number: "83", name: "Team Crest TC", team: "Canada", type: "Team Crest" },
  { number: "84", name: "Alphonso Davies ICON", team: "Canada", type: "Icon", persons: ["Alphonso Davies"] },
  { number: "85", name: "Dayne St. Clair", team: "Canada", persons: ["Dayne St. Clair"] },
  { number: "86", name: "Richie Laryea", team: "Canada", persons: ["Richie Laryea"] },
  { number: "87", name: "Derek Cornelius", team: "Canada", persons: ["Derek Cornelius"] },
  { number: "88", name: "Stephen Eustaquio", team: "Canada", persons: ["Stephen Eustaquio"] },
  { number: "89", name: "Ismael Kone", team: "Canada", persons: ["Ismael Kone"] },
  { number: "90", name: "Jonathan Osorio", team: "Canada", persons: ["Jonathan Osorio"] },
  { number: "91", name: "Jacob Shaffelburg", team: "Canada", persons: ["Jacob Shaffelburg"] },
  { number: "92", name: "Tajon Buchanan", team: "Canada", persons: ["Tajon Buchanan"] },
  { number: "93", name: "Cyle Larin", team: "Canada", persons: ["Cyle Larin"] },

  // Cape Verde (94-105)
  { number: "94", name: "Vozinha FF", team: "Cape Verde", type: "Fan Favourite", persons: ["Vozinha"] },
  { number: "95", name: "Team Crest TC", team: "Cape Verde", type: "Team Crest" },
  { number: "96", name: "Ryan Mendes ICON", team: "Cape Verde", type: "Icon", persons: ["Ryan Mendes"] },
  { number: "97", name: "Logan Costa", team: "Cape Verde", persons: ["Logan Costa"] },
  { number: "98", name: "Pico", team: "Cape Verde", persons: ["Pico"] },
  { number: "99", name: "Steven Moreira", team: "Cape Verde", persons: ["Steven Moreira"] },
  { number: "100", name: "Joao Paulo", team: "Cape Verde", persons: ["Joao Paulo"] },
  { number: "101", name: "Kevin Pina", team: "Cape Verde", persons: ["Kevin Pina"] },
  { number: "102", name: "Jamiro Monteiro", team: "Cape Verde", persons: ["Jamiro Monteiro"] },
  { number: "103", name: "Yannick Semedo", team: "Cape Verde", persons: ["Yannick Semedo"] },
  { number: "104", name: "Jovane Cabral", team: "Cape Verde", persons: ["Jovane Cabral"] },
  { number: "105", name: "Dailon Livramento", team: "Cape Verde", persons: ["Dailon Livramento"] },

  // Colombia (106-117)
  { number: "106", name: "Luis Diaz FF", team: "Colombia", type: "Fan Favourite", persons: ["Luis Diaz"] },
  { number: "107", name: "Team Crest TC", team: "Colombia", type: "Team Crest" },
  { number: "108", name: "James Rodriguez ICON", team: "Colombia", type: "Icon", persons: ["James Rodriguez"] },
  { number: "109", name: "Camilo Vargas", team: "Colombia", persons: ["Camilo Vargas"] },
  { number: "110", name: "Davinson Sanchez", team: "Colombia", persons: ["Davinson Sanchez"] },
  { number: "111", name: "Yerry Mina", team: "Colombia", persons: ["Yerry Mina"] },
  { number: "112", name: "Daniel Munoz", team: "Colombia", persons: ["Daniel Munoz"] },
  { number: "113", name: "Jefferson Lerma", team: "Colombia", persons: ["Jefferson Lerma"] },
  { number: "114", name: "Richard Rios", team: "Colombia", persons: ["Richard Rios"] },
  { number: "115", name: "Juan Fernando Quintero", team: "Colombia", persons: ["Juan Fernando Quintero"] },
  { number: "116", name: "Jhon Arias", team: "Colombia", persons: ["Jhon Arias"] },
  { number: "117", name: "Luis Suarez", team: "Colombia", persons: ["Luis Suarez"] },

  // Croatia (118-129)
  { number: "118", name: "Ivan Perisic FF", team: "Croatia", type: "Fan Favourite", persons: ["Ivan Perisic"] },
  { number: "119", name: "Team Crest TC", team: "Croatia", type: "Team Crest" },
  { number: "120", name: "Luka Modric ICON", team: "Croatia", type: "Icon", persons: ["Luka Modric"] },
  { number: "121", name: "Dominik Livakovic", team: "Croatia", persons: ["Dominik Livakovic"] },
  { number: "122", name: "Duje Caleta-Car", team: "Croatia", persons: ["Duje Caleta-Car"] },
  { number: "123", name: "Josko Gvardiol", team: "Croatia", persons: ["Josko Gvardiol"] },
  { number: "124", name: "Josip Stanisic", team: "Croatia", persons: ["Josip Stanisic"] },
  { number: "125", name: "Mateo Kovacic", team: "Croatia", persons: ["Mateo Kovacic"] },
  { number: "126", name: "Lovro Majer", team: "Croatia", persons: ["Lovro Majer"] },
  { number: "127", name: "Mario Pasalic", team: "Croatia", persons: ["Mario Pasalic"] },
  { number: "128", name: "Ante Budimir", team: "Croatia", persons: ["Ante Budimir"] },
  { number: "129", name: "Andrej Kramaric", team: "Croatia", persons: ["Andrej Kramaric"] },

  // Curacao (130-141)
  { number: "130", name: "Jurien Gaari FF", team: "Curacao", type: "Fan Favourite", persons: ["Jurien Gaari"] },
  { number: "131", name: "Team Crest TC", team: "Curacao", type: "Team Crest" },
  { number: "132", name: "Leandro Bacuna ICON", team: "Curacao", type: "Icon", persons: ["Leandro Bacuna"] },
  { number: "133", name: "Eloy Room", team: "Curacao", persons: ["Eloy Room"] },
  { number: "134", name: "Sherel Floranus", team: "Curacao", persons: ["Sherel Floranus"] },
  { number: "135", name: "Roshon Van Eijma", team: "Curacao", persons: ["Roshon Van Eijma"] },
  { number: "136", name: "Armando Obispo", team: "Curacao", persons: ["Armando Obispo"] },
  { number: "137", name: "Livano Comenencia", team: "Curacao", persons: ["Livano Comenencia"] },
  { number: "138", name: "Juninho Bacuna", team: "Curacao", persons: ["Juninho Bacuna"] },
  { number: "139", name: "Kenji Gorre", team: "Curacao", persons: ["Kenji Gorre"] },
  { number: "140", name: "Sontje Hansen", team: "Curacao", persons: ["Sontje Hansen"] },
  { number: "141", name: "Jearl Margaritha", team: "Curacao", persons: ["Jearl Margaritha"] },

  // Ecuador (142-153)
  { number: "142", name: "Moises Caicedo FF", team: "Ecuador", type: "Fan Favourite", persons: ["Moises Caicedo"] },
  { number: "143", name: "Team Crest TC", team: "Ecuador", type: "Team Crest" },
  { number: "144", name: "Enner Valencia ICON", team: "Ecuador", type: "Icon", persons: ["Enner Valencia"] },
  { number: "145", name: "Hernan Galindez", team: "Ecuador", persons: ["Hernan Galindez"] },
  { number: "146", name: "Piero Hincapie", team: "Ecuador", persons: ["Piero Hincapie"] },
  { number: "147", name: "Pervis Estupinan", team: "Ecuador", persons: ["Pervis Estupinan"] },
  { number: "148", name: "Willian Pacho", team: "Ecuador", persons: ["Willian Pacho"] },
  { number: "149", name: "Angelo Preciado", team: "Ecuador", persons: ["Angelo Preciado"] },
  { number: "150", name: "Joel Ordonez", team: "Ecuador", persons: ["Joel Ordonez"] },
  { number: "151", name: "Alan Franco", team: "Ecuador", persons: ["Alan Franco"] },
  { number: "152", name: "Gonzalo Plata", team: "Ecuador", persons: ["Gonzalo Plata"] },
  { number: "153", name: "Kevin Rodriguez", team: "Ecuador", persons: ["Kevin Rodriguez"] },

  // Egypt (154-165)
  { number: "154", name: "Omar Marmoush FF", team: "Egypt", type: "Fan Favourite", persons: ["Omar Marmoush"] },
  { number: "155", name: "Team Crest TC", team: "Egypt", type: "Team Crest" },
  { number: "156", name: "Mohamed Salah ICON", team: "Egypt", type: "Icon", persons: ["Mohamed Salah"] },
  { number: "157", name: "Mohamed El Shenawy", team: "Egypt", persons: ["Mohamed El Shenawy"] },
  { number: "158", name: "Mohamed Hany", team: "Egypt", persons: ["Mohamed Hany"] },
  { number: "159", name: "Mohamed Abdelmonem", team: "Egypt", persons: ["Mohamed Abdelmonem"] },
  { number: "160", name: "Ramy Rabia", team: "Egypt", persons: ["Ramy Rabia"] },
  { number: "161", name: "Marwan Attia", team: "Egypt", persons: ["Marwan Attia"] },
  { number: "162", name: "Zizo", team: "Egypt", persons: ["Zizo"] },
  { number: "163", name: "Hamdy Fathy", team: "Egypt", persons: ["Hamdy Fathy"] },
  { number: "164", name: "Mostafa Mohamed", team: "Egypt", persons: ["Mostafa Mohamed"] },
  { number: "165", name: "Trézéguet", team: "Egypt", persons: ["Trézéguet"] },

  // England (166-177)
  { number: "166", name: "Jude Bellingham FF", team: "England", type: "Fan Favourite", persons: ["Jude Bellingham"] },
  { number: "167", name: "Team Crest TC", team: "England", type: "Team Crest" },
  { number: "168", name: "Harry Kane ICON", team: "England", type: "Icon", persons: ["Harry Kane"] },
  { number: "169", name: "Jordan Pickford", team: "England", persons: ["Jordan Pickford"] },
  { number: "170", name: "Reece James", team: "England", persons: ["Reece James"] },
  { number: "171", name: "John Stones", team: "England", persons: ["John Stones"] },
  { number: "172", name: "Declan Rice", team: "England", persons: ["Declan Rice"] },
  { number: "173", name: "Jordan Henderson", team: "England", persons: ["Jordan Henderson"] },
  { number: "174", name: "Phil Foden", team: "England", persons: ["Phil Foden"] },
  { number: "175", name: "Bukayo Saka", team: "England", persons: ["Bukayo Saka"] },
  { number: "176", name: "Cole Palmer", team: "England", persons: ["Cole Palmer"] },
  { number: "177", name: "Marcus Rashford", team: "England", persons: ["Marcus Rashford"] },

  // France (178-189)
  { number: "178", name: "Ousmane Dembele FF", team: "France", type: "Fan Favourite", persons: ["Ousmane Dembele"] },
  { number: "179", name: "Team Crest TC", team: "France", type: "Team Crest" },
  { number: "180", name: "Kylian Mbappé ICON", team: "France", type: "Icon", persons: ["Kylian Mbappé"] },
  { number: "181", name: "Mike Maignan", team: "France", persons: ["Mike Maignan"] },
  { number: "182", name: "William Saliba", team: "France", persons: ["William Saliba"] },
  { number: "183", name: "Jules Kounde", team: "France", persons: ["Jules Kounde"] },
  { number: "184", name: "Theo Hernandez", team: "France", persons: ["Theo Hernandez"] },
  { number: "185", name: "Aurelien Tchouameni", team: "France", persons: ["Aurelien Tchouameni"] },
  { number: "186", name: "Eduardo Camavinga", team: "France", persons: ["Eduardo Camavinga"] },
  { number: "187", name: "Bradley Barcola", team: "France", persons: ["Bradley Barcola"] },
  { number: "188", name: "Marcus Thuram", team: "France", persons: ["Marcus Thuram"] },
  { number: "189", name: "Randal Kolo Muani", team: "France", persons: ["Randal Kolo Muani"] },

  // Germany (190-201)
  { number: "190", name: "Jamal Musiala FF", team: "Germany", type: "Fan Favourite", persons: ["Jamal Musiala"] },
  { number: "191", name: "Team Crest TC", team: "Germany", type: "Team Crest" },
  { number: "192", name: "Joshua Kimmich ICON", team: "Germany", type: "Icon", persons: ["Joshua Kimmich"] },
  { number: "193", name: "Marc-Andre ter Stegen", team: "Germany", persons: ["Marc-Andre ter Stegen"] },
  { number: "194", name: "Antonio Rudiger", team: "Germany", persons: ["Antonio Rudiger"] },
  { number: "195", name: "Jonathan Tah", team: "Germany", persons: ["Jonathan Tah"] },
  { number: "196", name: "Felix Nmecha", team: "Germany", persons: ["Felix Nmecha"] },
  { number: "197", name: "Leon Goretzka", team: "Germany", persons: ["Leon Goretzka"] },
  { number: "198", name: "Florian Wirtz", team: "Germany", persons: ["Florian Wirtz"] },
  { number: "199", name: "Serge Gnabry", team: "Germany", persons: ["Serge Gnabry"] },
  { number: "200", name: "Kai Havertz", team: "Germany", persons: ["Kai Havertz"] },
  { number: "201", name: "Leroy Sane", team: "Germany", persons: ["Leroy Sane"] },

  // Ghana (202-213)
  { number: "202", name: "Thomas Partey FF", team: "Ghana", type: "Fan Favourite", persons: ["Thomas Partey"] },
  { number: "203", name: "Team Crest TC", team: "Ghana", type: "Team Crest" },
  { number: "204", name: "Mohammed Kudus ICON", team: "Ghana", type: "Icon", persons: ["Mohammed Kudus"] },
  { number: "205", name: "Lawrence Ati-Zigi", team: "Ghana", persons: ["Lawrence Ati-Zigi"] },
  { number: "206", name: "Alidu Seidu", team: "Ghana", persons: ["Alidu Seidu"] },
  { number: "207", name: "Alexander Djiku", team: "Ghana", persons: ["Alexander Djiku"] },
  { number: "208", name: "Gideon Mensah", team: "Ghana", persons: ["Gideon Mensah"] },
  { number: "209", name: "Caleb Yirenkyi", team: "Ghana", persons: ["Caleb Yirenkyi"] },
  { number: "210", name: "Abdul Issahaku Fatawu", team: "Ghana", persons: ["Abdul Issahaku Fatawu"] },
  { number: "211", name: "Kamaldeen Sulemana", team: "Ghana", persons: ["Kamaldeen Sulemana"] },
  { number: "212", name: "Jordan Ayew", team: "Ghana", persons: ["Jordan Ayew"] },
  { number: "213", name: "Antoine Semenyo", team: "Ghana", persons: ["Antoine Semenyo"] },

  // Haiti (214-225)
  { number: "214", name: "Frantzdy Pierrot FF", team: "Haiti", type: "Fan Favourite", persons: ["Frantzdy Pierrot"] },
  { number: "215", name: "Team Crest TC", team: "Haiti", type: "Team Crest" },
  { number: "216", name: "Duckens Nazon ICON", team: "Haiti", type: "Icon", persons: ["Duckens Nazon"] },
  { number: "217", name: "Johny Placide", team: "Haiti", persons: ["Johny Placide"] },
  { number: "218", name: "Ricardo Ade", team: "Haiti", persons: ["Ricardo Ade"] },
  { number: "219", name: "Carlens Arcus", team: "Haiti", persons: ["Carlens Arcus"] },
  { number: "220", name: "Hannes Delcroix", team: "Haiti", persons: ["Hannes Delcroix"] },
  { number: "221", name: "Leverton Pierre", team: "Haiti", persons: ["Leverton Pierre"] },
  { number: "222", name: "Danley Jean Jacques", team: "Haiti", persons: ["Danley Jean Jacques"] },
  { number: "223", name: "Jean-Ricner Bellegarde", team: "Haiti", persons: ["Jean-Ricner Bellegarde"] },
  { number: "224", name: "Ruben Providence", team: "Haiti", persons: ["Ruben Providence"] },
  { number: "225", name: "Don Deedson Louicius", team: "Haiti", persons: ["Don Deedson Louicius"] },

  // Iran (226-237)
  { number: "226", name: "Mehdi Taremi FF", team: "Iran", type: "Fan Favourite", persons: ["Mehdi Taremi"] },
  { number: "227", name: "Team Crest TC", team: "Iran", type: "Team Crest" },
  { number: "228", name: "Sardar Azmoun ICON", team: "Iran", type: "Icon", persons: ["Sardar Azmoun"] },
  { number: "229", name: "Alireza Beiranvand", team: "Iran", persons: ["Alireza Beiranvand"] },
  { number: "230", name: "Shoja Khalilzadeh", team: "Iran", persons: ["Shoja Khalilzadeh"] },
  { number: "231", name: "Milad Mohammadi", team: "Iran", persons: ["Milad Mohammadi"] },
  { number: "232", name: "Ramin Rezaeian", team: "Iran", persons: ["Ramin Rezaeian"] },
  { number: "233", name: "Hossein Kanaani", team: "Iran", persons: ["Hossein Kanaani"] },
  { number: "234", name: "Saeid Ezatolahi", team: "Iran", persons: ["Saeid Ezatolahi"] },
  { number: "235", name: "Saman Ghoddos", team: "Iran", persons: ["Saman Ghoddos"] },
  { number: "236", name: "Mohammad Mohebi", team: "Iran", persons: ["Mohammad Mohebi"] },
  { number: "237", name: "Alireza Jahanbakhsh", team: "Iran", persons: ["Alireza Jahanbakhsh"] },

  // Cote D'Ivoire (238-249)
  { number: "238", name: "Franck Kessie FF", team: "Cote D'Ivoire", type: "Fan Favourite", persons: ["Franck Kessie"] },
  { number: "239", name: "Team Crest TC", team: "Cote D'Ivoire", type: "Team Crest" },
  { number: "240", name: "Sebastien Haller ICON", team: "Cote D'Ivoire", type: "Icon", persons: ["Sebastien Haller"] },
  { number: "241", name: "Yahia Fofana", team: "Cote D'Ivoire", persons: ["Yahia Fofana"] },
  { number: "242", name: "Ghislain Konan", team: "Cote D'Ivoire", persons: ["Ghislain Konan"] },
  { number: "243", name: "Odilon Kossounou", team: "Cote D'Ivoire", persons: ["Odilon Kossounou"] },
  { number: "244", name: "Evan N'Dicka", team: "Cote D'Ivoire", persons: ["Evan N'Dicka"] },
  { number: "245", name: "Wilfried Singo", team: "Cote D'Ivoire", persons: ["Wilfried Singo"] },
  { number: "246", name: "Ibrahim Sangare", team: "Cote D'Ivoire", persons: ["Ibrahim Sangare"] },
  { number: "247", name: "Nicolas Pepe", team: "Cote D'Ivoire", persons: ["Nicolas Pepe"] },
  { number: "248", name: "Simon Adingra", team: "Cote D'Ivoire", persons: ["Simon Adingra"] },
  { number: "249", name: "Oumar Diakite", team: "Cote D'Ivoire", persons: ["Oumar Diakite"] },

  // Japan (250-261)
  { number: "250", name: "Takumi Minamino FF", team: "Japan", type: "Fan Favourite", persons: ["Takumi Minamino"] },
  { number: "251", name: "Team Crest TC", team: "Japan", type: "Team Crest" },
  { number: "252", name: "Takefusa Kubo ICON", team: "Japan", type: "Icon", persons: ["Takefusa Kubo"] },
  { number: "253", name: "Zion Suzuki", team: "Japan", persons: ["Zion Suzuki"] },
  { number: "254", name: "Tsuyoshi Watanabe", team: "Japan", persons: ["Tsuyoshi Watanabe"] },
  { number: "255", name: "Kaishu Sano", team: "Japan", persons: ["Kaishu Sano"] },
  { number: "256", name: "Ao Tanaka", team: "Japan", persons: ["Ao Tanaka"] },
  { number: "257", name: "Daichi Kamada", team: "Japan", persons: ["Daichi Kamada"] },
  { number: "258", name: "Ritsu Doan", team: "Japan", persons: ["Ritsu Doan"] },
  { number: "259", name: "Keito Nakamura", team: "Japan", persons: ["Keito Nakamura"] },
  { number: "260", name: "Shuto Machino", team: "Japan", persons: ["Shuto Machino"] },
  { number: "261", name: "Ayase Ueda", team: "Japan", persons: ["Ayase Ueda"] },

  // Jordan (262-273)
  { number: "262", name: "Yazan Al-Naimat FF", team: "Jordan", type: "Fan Favourite", persons: ["Yazan Al-Naimat"] },
  { number: "263", name: "Team Crest TC", team: "Jordan", type: "Team Crest" },
  { number: "264", name: "Musa Al-Taamari ICON", team: "Jordan", type: "Icon", persons: ["Musa Al-Taamari"] },
  { number: "265", name: "Yazeed Abulaila", team: "Jordan", persons: ["Yazeed Abulaila"] },
  { number: "266", name: "Mohammad Abu Hashish", team: "Jordan", persons: ["Mohammad Abu Hashish"] },
  { number: "267", name: "Yazan Al-Arab", team: "Jordan", persons: ["Yazan Al-Arab"] },
  { number: "268", name: "Abdallah Nasib", team: "Jordan", persons: ["Abdallah Nasib"] },
  { number: "269", name: "Ibrahim Sadeh", team: "Jordan", persons: ["Ibrahim Sadeh"] },
  { number: "270", name: "Nizar Al-Rashdan", team: "Jordan", persons: ["Nizar Al-Rashdan"] },
  { number: "271", name: "Noor Al-Rawabdeh", team: "Jordan", persons: ["Noor Al-Rawabdeh"] },
  { number: "272", name: "Mahmoud Al-Mardi", team: "Jordan", persons: ["Mahmoud Al-Mardi"] },
  { number: "273", name: "Ali Olwan", team: "Jordan", persons: ["Ali Olwan"] },

  // Korea Republic (274-285)
  { number: "274", name: "Min-jae Kim FF", team: "Korea Republic", type: "Fan Favourite", persons: ["Min-jae Kim"] },
  { number: "275", name: "Team Crest TC", team: "Korea Republic", type: "Team Crest" },
  { number: "276", name: "Heung-min Son ICON", team: "Korea Republic", type: "Icon", persons: ["Heung-min Son"] },
  { number: "277", name: "Hyeon-woo Jo", team: "Korea Republic", persons: ["Hyeon-woo Jo"] },
  { number: "278", name: "Young-woo Seol", team: "Korea Republic", persons: ["Young-woo Seol"] },
  { number: "279", name: "Yu-min Cho", team: "Korea Republic", persons: ["Yu-min Cho"] },
  { number: "280", name: "Tae-seok Lee", team: "Korea Republic", persons: ["Tae-seok Lee"] },
  { number: "281", name: "In-beom Hwang", team: "Korea Republic", persons: ["In-beom Hwang"] },
  { number: "282", name: "Jae-sung Lee", team: "Korea Republic", persons: ["Jae-sung Lee"] },
  { number: "283", name: "Kang-in Lee", team: "Korea Republic", persons: ["Kang-in Lee"] },
  { number: "284", name: "Hyeon-gyu Oh", team: "Korea Republic", persons: ["Hyeon-gyu Oh"] },
  { number: "285", name: "Hee-chan Hwang", team: "Korea Republic", persons: ["Hee-chan Hwang"] },

  // Mexico (286-297)
  { number: "286", name: "Edson Alvarez FF", team: "Mexico", type: "Fan Favourite", persons: ["Edson Alvarez"] },
  { number: "287", name: "Team Crest TC", team: "Mexico", type: "Team Crest" },
  { number: "288", name: "Raul Jimenez ICON", team: "Mexico", type: "Icon", persons: ["Raul Jimenez"] },
  { number: "289", name: "Luis Malagon", team: "Mexico", persons: ["Luis Malagon"] },
  { number: "290", name: "Israel Reyes", team: "Mexico", persons: ["Israel Reyes"] },
  { number: "291", name: "Johan Vasquez", team: "Mexico", persons: ["Johan Vasquez"] },
  { number: "292", name: "Cesar Montes", team: "Mexico", persons: ["Cesar Montes"] },
  { number: "293", name: "Jesus Gallardo", team: "Mexico", persons: ["Jesus Gallardo"] },
  { number: "294", name: "Carlos Rodriguez", team: "Mexico", persons: ["Carlos Rodriguez"] },
  { number: "295", name: "Orbelin Pineda", team: "Mexico", persons: ["Orbelin Pineda"] },
  { number: "296", name: "Hirving Lozano", team: "Mexico", persons: ["Hirving Lozano"] },
  { number: "297", name: "Santiago Gimenez", team: "Mexico", persons: ["Santiago Gimenez"] },

  // Morocco (298-309)
  { number: "298", name: "Youssef En-Nesyri FF", team: "Morocco", type: "Fan Favourite", persons: ["Youssef En-Nesyri"] },
  { number: "299", name: "Team Crest TC", team: "Morocco", type: "Team Crest" },
  { number: "300", name: "Achraf Hakimi ICON", team: "Morocco", type: "Icon", persons: ["Achraf Hakimi"] },
  { number: "301", name: "Yassine Bounou", team: "Morocco", persons: ["Yassine Bounou"] },
  { number: "302", name: "Noussair Mazraoui", team: "Morocco", persons: ["Noussair Mazraoui"] },
  { number: "303", name: "Nayef Aguerd", team: "Morocco", persons: ["Nayef Aguerd"] },
  { number: "304", name: "Sofyan Amrabat", team: "Morocco", persons: ["Sofyan Amrabat"] },
  { number: "305", name: "Eliesse Ben Seghir", team: "Morocco", persons: ["Eliesse Ben Seghir"] },
  { number: "306", name: "Ismael Saibari", team: "Morocco", persons: ["Ismael Saibari"] },
  { number: "307", name: "Brahim Diaz", team: "Morocco", persons: ["Brahim Diaz"] },
  { number: "308", name: "Abde Ezzalzouli", team: "Morocco", persons: ["Abde Ezzalzouli"] },
  { number: "309", name: "Ayoub El Kaabi", team: "Morocco", persons: ["Ayoub El Kaabi"] },

  // Netherlands (310-321)
  { number: "310", name: "Memphis Depay FF", team: "Netherlands", type: "Fan Favourite", persons: ["Memphis Depay"] },
  { number: "311", name: "Team Crest TC", team: "Netherlands", type: "Team Crest" },
  { number: "312", name: "Virgil van Dijk ICON", team: "Netherlands", type: "Icon", persons: ["Virgil van Dijk"] },
  { number: "313", name: "Bart Verbruggen", team: "Netherlands", persons: ["Bart Verbruggen"] },
  { number: "314", name: "Nathan Ake", team: "Netherlands", persons: ["Nathan Ake"] },
  { number: "315", name: "Jeremie Frimpong", team: "Netherlands", persons: ["Jeremie Frimpong"] },
  { number: "316", name: "Denzel Dumfries", team: "Netherlands", persons: ["Denzel Dumfries"] },
  { number: "317", name: "Tijjani Reijnders", team: "Netherlands", persons: ["Tijjani Reijnders"] },
  { number: "318", name: "Ryan Gravenberch", team: "Netherlands", persons: ["Ryan Gravenberch"] },
  { number: "319", name: "Cody Gakpo", team: "Netherlands", persons: ["Cody Gakpo"] },
  { number: "320", name: "Donyell Malen", team: "Netherlands", persons: ["Donyell Malen"] },
  { number: "321", name: "Wout Weghorst", team: "Netherlands", persons: ["Wout Weghorst"] },

  // New Zealand (322-333)
  { number: "322", name: "Marko Stamenic FF", team: "New Zealand", type: "Fan Favourite", persons: ["Marko Stamenic"] },
  { number: "323", name: "Team Crest TC", team: "New Zealand", type: "Team Crest" },
  { number: "324", name: "Chris Wood ICON", team: "New Zealand", type: "Icon", persons: ["Chris Wood"] },
  { number: "325", name: "Max Crocombe", team: "New Zealand", persons: ["Max Crocombe"] },
  { number: "326", name: "Michael Boxall", team: "New Zealand", persons: ["Michael Boxall"] },
  { number: "327", name: "Liberato Cacace", team: "New Zealand", persons: ["Liberato Cacace"] },
  { number: "328", name: "Tim Payne", team: "New Zealand", persons: ["Tim Payne"] },
  { number: "329", name: "Finn Surman", team: "New Zealand", persons: ["Finn Surman"] },
  { number: "330", name: "Joe Bell", team: "New Zealand", persons: ["Joe Bell"] },
  { number: "331", name: "Sarpreet Singh", team: "New Zealand", persons: ["Sarpreet Singh"] },
  { number: "332", name: "Matt Garbett", team: "New Zealand", persons: ["Matt Garbett"] },
  { number: "333", name: "Elijah Just", team: "New Zealand", persons: ["Elijah Just"] },

  // Norway (334-345)
  { number: "334", name: "Martin Odegaard FF", team: "Norway", type: "Fan Favourite", persons: ["Martin Odegaard"] },
  { number: "335", name: "Team Crest TC", team: "Norway", type: "Team Crest" },
  { number: "336", name: "Erling Haaland ICON", team: "Norway", type: "Icon", persons: ["Erling Haaland"] },
  { number: "337", name: "Orjan Nyland", team: "Norway", persons: ["Orjan Nyland"] },
  { number: "338", name: "Julian Ryerson", team: "Norway", persons: ["Julian Ryerson"] },
  { number: "339", name: "Kristoffer Vassbakk Ajer", team: "Norway", persons: ["Kristoffer Vassbakk Ajer"] },
  { number: "340", name: "David Moller Wolfe", team: "Norway", persons: ["David Moller Wolfe"] },
  { number: "341", name: "Sander Berge", team: "Norway", persons: ["Sander Berge"] },
  { number: "342", name: "Patrick Berg", team: "Norway", persons: ["Patrick Berg"] },
  { number: "343", name: "Antonio Nusa", team: "Norway", persons: ["Antonio Nusa"] },
  { number: "344", name: "Oscar Bobb", team: "Norway", persons: ["Oscar Bobb"] },
  { number: "345", name: "Alexander Sorloth", team: "Norway", persons: ["Alexander Sorloth"] },

  // Panama (346-357)
  { number: "346", name: "Michael Amir Murillo FF", team: "Panama", type: "Fan Favourite", persons: ["Michael Amir Murillo"] },
  { number: "347", name: "Team Crest TC", team: "Panama", type: "Team Crest" },
  { number: "348", name: "Anibal Godoy ICON", team: "Panama", type: "Icon", persons: ["Anibal Godoy"] },
  { number: "349", name: "Orlando Mosquera", team: "Panama", persons: ["Orlando Mosquera"] },
  { number: "350", name: "Andres Andrade", team: "Panama", persons: ["Andres Andrade"] },
  { number: "351", name: "Fidel Escobar", team: "Panama", persons: ["Fidel Escobar"] },
  { number: "352", name: "Cristian Martínez", team: "Panama", persons: ["Cristian Martínez"] },
  { number: "353", name: "Adalberto Carrasquilla", team: "Panama", persons: ["Adalberto Carrasquilla"] },
  { number: "354", name: "Edgar Barcenas", team: "Panama", persons: ["Edgar Barcenas"] },
  { number: "355", name: "Jose Fajardo", team: "Panama", persons: ["Jose Fajardo"] },
  { number: "356", name: "Ismael Díaz", team: "Panama", persons: ["Ismael Díaz"] },
  { number: "357", name: "José Luis Rodríguez", team: "Panama", persons: ["José Luis Rodríguez"] },

  // Paraguay (358-369)
  { number: "358", name: "Gustavo Gomez FF", team: "Paraguay", type: "Fan Favourite", persons: ["Gustavo Gomez"] },
  { number: "359", name: "Team Crest TC", team: "Paraguay", type: "Team Crest" },
  { number: "360", name: "Miguel Almiron ICON", team: "Paraguay", type: "Icon", persons: ["Miguel Almiron"] },
  { number: "361", name: "Roberto Fernandez", team: "Paraguay", persons: ["Roberto Fernandez"] },
  { number: "362", name: "Juan Jose Caceres", team: "Paraguay", persons: ["Juan Jose Caceres"] },
  { number: "363", name: "Omar Alderete", team: "Paraguay", persons: ["Omar Alderete"] },
  { number: "364", name: "Junior Alonso", team: "Paraguay", persons: ["Junior Alonso"] },
  { number: "365", name: "Andres Cubas", team: "Paraguay", persons: ["Andres Cubas"] },
  { number: "366", name: "Mathias Villasanti", team: "Paraguay", persons: ["Mathias Villasanti"] },
  { number: "367", name: "Julio Enciso", team: "Paraguay", persons: ["Julio Enciso"] },
  { number: "368", name: "Ramon Sosa", team: "Paraguay", persons: ["Ramon Sosa"] },
  { number: "369", name: "Antonio Sanabria", team: "Paraguay", persons: ["Antonio Sanabria"] },

  // Portugal (370-381)
  { number: "370", name: "Vitinha FF", team: "Portugal", type: "Fan Favourite", persons: ["Vitinha"] },
  { number: "371", name: "Team Crest TC", team: "Portugal", type: "Team Crest" },
  { number: "372", name: "Cristiano Ronaldo ICON", team: "Portugal", type: "Icon", persons: ["Cristiano Ronaldo"] },
  { number: "373", name: "Diogo Costa", team: "Portugal", persons: ["Diogo Costa"] },
  { number: "374", name: "Ruben Dias", team: "Portugal", persons: ["Ruben Dias"] },
  { number: "375", name: "Nuno Mendes", team: "Portugal", persons: ["Nuno Mendes"] },
  { number: "376", name: "Bernardo Silva", team: "Portugal", persons: ["Bernardo Silva"] },
  { number: "377", name: "Bruno Fernandes", team: "Portugal", persons: ["Bruno Fernandes"] },
  { number: "378", name: "Ruben Neves", team: "Portugal", persons: ["Ruben Neves"] },
  { number: "379", name: "Francisco Conceicao", team: "Portugal", persons: ["Francisco Conceicao"] },
  { number: "380", name: "Pedro Neto", team: "Portugal", persons: ["Pedro Neto"] },
  { number: "381", name: "Rafael Leao", team: "Portugal", persons: ["Rafael Leao"] },

  // Qatar (382-393)
  { number: "382", name: "Almoez Ali FF", team: "Qatar", type: "Fan Favourite", persons: ["Almoez Ali"] },
  { number: "383", name: "Team Crest TC", team: "Qatar", type: "Team Crest" },
  { number: "384", name: "Hasan Al-Haydos ICON", team: "Qatar", type: "Icon", persons: ["Hasan Al-Haydos"] },
  { number: "385", name: "Meshaal Barsham", team: "Qatar", persons: ["Meshaal Barsham"] },
  { number: "386", name: "Boualem Khoukhi", team: "Qatar", persons: ["Boualem Khoukhi"] },
  { number: "387", name: "Lucas Mendes", team: "Qatar", persons: ["Lucas Mendes"] },
  { number: "388", name: "Pedro Miguel", team: "Qatar", persons: ["Pedro Miguel"] },
  { number: "389", name: "Homam Ahmed", team: "Qatar", persons: ["Homam Ahmed"] },
  { number: "390", name: "Ahmed Fathy", team: "Qatar", persons: ["Ahmed Fathy"] },
  { number: "391", name: "Edmilson Junior", team: "Qatar", persons: ["Edmilson Junior"] },
  { number: "392", name: "Ahmed Al-Ganehi", team: "Qatar", persons: ["Ahmed Al-Ganehi"] },
  { number: "393", name: "Akram Hassan Afif", team: "Qatar", persons: ["Akram Hassan Afif"] },

  // Saudi Arabia (394-405)
  { number: "394", name: "Firas Al-Buraikan FF", team: "Saudi Arabia", type: "Fan Favourite", persons: ["Firas Al-Buraikan"] },
  { number: "395", name: "Team Crest TC", team: "Saudi Arabia", type: "Team Crest" },
  { number: "396", name: "Salem Al-Dawsari ICON", team: "Saudi Arabia", type: "Icon", persons: ["Salem Al-Dawsari"] },
  { number: "397", name: "Nawaf Al-Aqidi", team: "Saudi Arabia", persons: ["Nawaf Al-Aqidi"] },
  { number: "398", name: "Hassan Al-Tambakti", team: "Saudi Arabia", persons: ["Hassan Al-Tambakti"] },
  { number: "399", name: "Jehad Thikri", team: "Saudi Arabia", persons: ["Jehad Thikri"] },
  { number: "400", name: "Saud Abdulhamid", team: "Saudi Arabia", persons: ["Saud Abdulhamid"] },
  { number: "401", name: "Nasser Al-Dawsari", team: "Saudi Arabia", persons: ["Nasser Al-Dawsari"] },
  { number: "402", name: "Abdullah Al-Khaibari", team: "Saudi Arabia", persons: ["Abdullah Al-Khaibari"] },
  { number: "403", name: "Musab Al-Juwayr", team: "Saudi Arabia", persons: ["Musab Al-Juwayr"] },
  { number: "404", name: "Saleh Abu Al-Shamat", team: "Saudi Arabia", persons: ["Saleh Abu Al-Shamat"] },
  { number: "405", name: "Saleh Al-Sheheri", team: "Saudi Arabia", persons: ["Saleh Al-Sheheri"] },

  // Scotland (406-417)
  { number: "406", name: "Scott McTominay FF", team: "Scotland", type: "Fan Favourite", persons: ["Scott McTominay"] },
  { number: "407", name: "Team Crest TC", team: "Scotland", type: "Team Crest" },
  { number: "408", name: "Andrew Robertson ICON", team: "Scotland", type: "Icon", persons: ["Andrew Robertson"] },
  { number: "409", name: "Angus Gunn", team: "Scotland", persons: ["Angus Gunn"] },
  { number: "410", name: "Kieran Tierney", team: "Scotland", persons: ["Kieran Tierney"] },
  { number: "411", name: "Grant Hanley", team: "Scotland", persons: ["Grant Hanley"] },
  { number: "412", name: "Billy Gilmour", team: "Scotland", persons: ["Billy Gilmour"] },
  { number: "413", name: "Lewis Ferguson", team: "Scotland", persons: ["Lewis Ferguson"] },
  { number: "414", name: "Ryan Christie", team: "Scotland", persons: ["Ryan Christie"] },
  { number: "415", name: "John McGinn", team: "Scotland", persons: ["John McGinn"] },
  { number: "416", name: "Ben Gannon-Doak", team: "Scotland", persons: ["Ben Gannon-Doak"] },
  { number: "417", name: "Che Adams", team: "Scotland", persons: ["Che Adams"] },

  // Senegal (418-429)
  { number: "418", name: "Kalidou Koulibaly FF", team: "Senegal", type: "Fan Favourite", persons: ["Kalidou Koulibaly"] },
  { number: "419", name: "Team Crest TC", team: "Senegal", type: "Team Crest" },
  { number: "420", name: "Sadio Mane ICON", team: "Senegal", type: "Icon", persons: ["Sadio Mane"] },
  { number: "421", name: "Edouard Mendy", team: "Senegal", persons: ["Edouard Mendy"] },
  { number: "422", name: "Moussa Niakhate", team: "Senegal", persons: ["Moussa Niakhate"] },
  { number: "423", name: "El Hadji Malick Diouf", team: "Senegal", persons: ["El Hadji Malick Diouf"] },
  { number: "424", name: "Idrissa Gana Gueye", team: "Senegal", persons: ["Idrissa Gana Gueye"] },
  { number: "425", name: "Pape Matar Sarr", team: "Senegal", persons: ["Pape Matar Sarr"] },
  { number: "426", name: "Iliman Ndiaye", team: "Senegal", persons: ["Iliman Ndiaye"] },
  { number: "427", name: "Krepin Diatta", team: "Senegal", persons: ["Krepin Diatta"] },
  { number: "428", name: "Ismaila Sarr", team: "Senegal", persons: ["Ismaila Sarr"] },
  { number: "429", name: "Nicolas Jackson", team: "Senegal", persons: ["Nicolas Jackson"] },

  // South Africa (430-441)
  { number: "430", name: "Lyle Foster FF", team: "South Africa", type: "Fan Favourite", persons: ["Lyle Foster"] },
  { number: "431", name: "Team Crest TC", team: "South Africa", type: "Team Crest" },
  { number: "432", name: "Ronwen Williams ICON", team: "South Africa", type: "Icon", persons: ["Ronwen Williams"] },
  { number: "433", name: "Siyabonga Ngezana", team: "South Africa", persons: ["Siyabonga Ngezana"] },
  { number: "434", name: "Aubrey Modiba", team: "South Africa", persons: ["Aubrey Modiba"] },
  { number: "435", name: "Mbekezeli Mbokazi", team: "South Africa", persons: ["Mbekezeli Mbokazi"] },
  { number: "436", name: "Khuliso Mudau", team: "South Africa", persons: ["Khuliso Mudau"] },
  { number: "437", name: "Teboho Mokoena", team: "South Africa", persons: ["Teboho Mokoena"] },
  { number: "438", name: "Yaya Sithole", team: "South Africa", persons: ["Yaya Sithole"] },
  { number: "439", name: "Themba Zwane", team: "South Africa", persons: ["Themba Zwane"] },
  { number: "440", name: "Oswin Appollis", team: "South Africa", persons: ["Oswin Appollis"] },
  { number: "441", name: "Iqraam Rayners", team: "South Africa", persons: ["Iqraam Rayners"] },

  // Spain (442-453)
  { number: "442", name: "Lamine Yamal FF", team: "Spain", type: "Fan Favourite", persons: ["Lamine Yamal"] },
  { number: "443", name: "Team Crest TC", team: "Spain", type: "Team Crest" },
  { number: "444", name: "Rodri ICON", team: "Spain", type: "Icon", persons: ["Rodri"] },
  { number: "445", name: "Unai Simon", team: "Spain", persons: ["Unai Simon"] },
  { number: "446", name: "Robin Le Normand", team: "Spain", persons: ["Robin Le Normand"] },
  { number: "447", name: "Dean Huijsen", team: "Spain", persons: ["Dean Huijsen"] },
  { number: "448", name: "Marc Cucurella", team: "Spain", persons: ["Marc Cucurella"] },
  { number: "449", name: "Martin Zubimendi", team: "Spain", persons: ["Martin Zubimendi"] },
  { number: "450", name: "Pedri", team: "Spain", persons: ["Pedri"] },
  { number: "451", name: "Fabian Ruiz", team: "Spain", persons: ["Fabian Ruiz"] },
  { number: "452", name: "Nico Williams", team: "Spain", persons: ["Nico Williams"] },
  { number: "453", name: "Mikel Oyarzabal", team: "Spain", persons: ["Mikel Oyarzabal"] },

  // Switzerland (454-465)
  { number: "454", name: "Manuel Akanji FF", team: "Switzerland", type: "Fan Favourite", persons: ["Manuel Akanji"] },
  { number: "455", name: "Team Crest TC", team: "Switzerland", type: "Team Crest" },
  { number: "456", name: "Granit Xhaka ICON", team: "Switzerland", type: "Icon", persons: ["Granit Xhaka"] },
  { number: "457", name: "Gregor Kobel", team: "Switzerland", persons: ["Gregor Kobel"] },
  { number: "458", name: "Nico Elvedi", team: "Switzerland", persons: ["Nico Elvedi"] },
  { number: "459", name: "Ricardo Rodriguez", team: "Switzerland", persons: ["Ricardo Rodriguez"] },
  { number: "460", name: "Silvan Widmer", team: "Switzerland", persons: ["Silvan Widmer"] },
  { number: "461", name: "Denis Zakaria", team: "Switzerland", persons: ["Denis Zakaria"] },
  { number: "462", name: "Remo Freuler", team: "Switzerland", persons: ["Remo Freuler"] },
  { number: "463", name: "Breel Embolo", team: "Switzerland", persons: ["Breel Embolo"] },
  { number: "464", name: "Ruben Vargas", team: "Switzerland", persons: ["Ruben Vargas"] },
  { number: "465", name: "Dan Ndoye", team: "Switzerland", persons: ["Dan Ndoye"] },

  // Tunisia (466-477)
  { number: "466", name: "Ferjani Sassi FF", team: "Tunisia", type: "Fan Favourite", persons: ["Ferjani Sassi"] },
  { number: "467", name: "Team Crest TC", team: "Tunisia", type: "Team Crest" },
  { number: "468", name: "Ellyes Skhiri ICON", team: "Tunisia", type: "Icon", persons: ["Ellyes Skhiri"] },
  { number: "469", name: "Aymen Dahmen", team: "Tunisia", persons: ["Aymen Dahmen"] },
  { number: "470", name: "Montassar Talbi", team: "Tunisia", persons: ["Montassar Talbi"] },
  { number: "471", name: "Yassine Meriah", team: "Tunisia", persons: ["Yassine Meriah"] },
  { number: "472", name: "Ali Abdi", team: "Tunisia", persons: ["Ali Abdi"] },
  { number: "473", name: "Aissa Laidouni", team: "Tunisia", persons: ["Aissa Laidouni"] },
  { number: "474", name: "Hannibal Mejbri", team: "Tunisia", persons: ["Hannibal Mejbri"] },
  { number: "475", name: "Naim Sliti", team: "Tunisia", persons: ["Naim Sliti"] },
  { number: "476", name: "Elias Achouri", team: "Tunisia", persons: ["Elias Achouri"] },
  { number: "477", name: "Hazem Mastouri", team: "Tunisia", persons: ["Hazem Mastouri"] },

  // USA (478-489)
  { number: "478", name: "Weston McKennie FF", team: "USA", type: "Fan Favourite", persons: ["Weston McKennie"] },
  { number: "479", name: "Team Crest TC", team: "USA", type: "Team Crest" },
  { number: "480", name: "Christian Pulisic ICON", team: "USA", type: "Icon", persons: ["Christian Pulisic"] },
  { number: "481", name: "Matt Freese", team: "USA", persons: ["Matt Freese"] },
  { number: "482", name: "Chris Richards", team: "USA", persons: ["Chris Richards"] },
  { number: "483", name: "Tim Ream", team: "USA", persons: ["Tim Ream"] },
  { number: "484", name: "Antonee Robinson", team: "USA", persons: ["Antonee Robinson"] },
  { number: "485", name: "Tanner Tessmann", team: "USA", persons: ["Tanner Tessmann"] },
  { number: "486", name: "Tyler Adams", team: "USA", persons: ["Tyler Adams"] },
  { number: "487", name: "Timothy Weah", team: "USA", persons: ["Timothy Weah"] },
  { number: "488", name: "Malik Tillman", team: "USA", persons: ["Malik Tillman"] },
  { number: "489", name: "Folarin Balogun", team: "USA", persons: ["Folarin Balogun"] },

  // Uruguay (490-501)
  { number: "490", name: "Jose Maria Gimenez FF", team: "Uruguay", type: "Fan Favourite", persons: ["Jose Maria Gimenez"] },
  { number: "491", name: "Team Crest TC", team: "Uruguay", type: "Team Crest" },
  { number: "492", name: "Federico Valverde ICON", team: "Uruguay", type: "Icon", persons: ["Federico Valverde"] },
  { number: "493", name: "Sergio Rochet", team: "Uruguay", persons: ["Sergio Rochet"] },
  { number: "494", name: "Ronald Araújo", team: "Uruguay", persons: ["Ronald Araújo"] },
  { number: "495", name: "Sebastián Cáceres", team: "Uruguay", persons: ["Sebastián Cáceres"] },
  { number: "496", name: "Mathias Olivera", team: "Uruguay", persons: ["Mathias Olivera"] },
  { number: "497", name: "Nahitan Nandez", team: "Uruguay", persons: ["Nahitan Nandez"] },
  { number: "498", name: "Rodrigo Bentancur", team: "Uruguay", persons: ["Rodrigo Bentancur"] },
  { number: "499", name: "Manuel Ugarte", team: "Uruguay", persons: ["Manuel Ugarte"] },
  { number: "500", name: "Facundo Pellistri", team: "Uruguay", persons: ["Facundo Pellistri"] },
  { number: "501", name: "Darwin Núñez", team: "Uruguay", persons: ["Darwin Núñez"] },

  // Uzbekistan (502-513)
  { number: "502", name: "Abdukodir Khusanov FF", team: "Uzbekistan", type: "Fan Favourite", persons: ["Abdukodir Khusanov"] },
  { number: "503", name: "Team Crest TC", team: "Uzbekistan", type: "Team Crest" },
  { number: "504", name: "Eldor Shomurodov ICON", team: "Uzbekistan", type: "Icon", persons: ["Eldor Shomurodov"] },
  { number: "505", name: "Utkir Yusupov", team: "Uzbekistan", persons: ["Utkir Yusupov"] },
  { number: "506", name: "Farrukh Sayfiev", team: "Uzbekistan", persons: ["Farrukh Sayfiev"] },
  { number: "507", name: "Sherzod Nasrullaev", team: "Uzbekistan", persons: ["Sherzod Nasrullaev"] },
  { number: "508", name: "Husniddin Aliqulov", team: "Uzbekistan", persons: ["Husniddin Aliqulov"] },
  { number: "509", name: "Rustam Ashurmatov", team: "Uzbekistan", persons: ["Rustam Ashurmatov"] },
  { number: "510", name: "Khojiakbar Alijonov", team: "Uzbekistan", persons: ["Khojiakbar Alijonov"] },
  { number: "511", name: "Odiljon Hamrobekov", team: "Uzbekistan", persons: ["Odiljon Hamrobekov"] },
  { number: "512", name: "Otabek Shukurov", team: "Uzbekistan", persons: ["Otabek Shukurov"] },
  { number: "513", name: "Abbosbek Fayzullaev", team: "Uzbekistan", persons: ["Abbosbek Fayzullaev"] },

  // Confederation Qualifiers (514-549)
  { number: "514", name: "Italy-Northern Ireland / Wales-Bosnia CON", team: "Italy / Northern Ireland / Wales / Bosnia and Herzegovina", type: "Confederation" },
  { number: "515", name: "Ukraine-Sweden / Poland-Albania CON", team: "Ukraine / Sweden / Poland / Albania", type: "Confederation" },
  { number: "516", name: "Turkey-Romania / Slovakia-Kosovo CON", team: "Turkey / Romania / Slovakia / Kosovo", type: "Confederation" },
  { number: "517", name: "Denmark-North Macedonia / Czech Republic-Republic of Ireland CON", team: "Denmark / North Macedonia / Czech Republic / Republic of Ireland", type: "Confederation" },
  { number: "518", name: "New Caledonia-Jamaica / DR Congo CON", team: "New Caledonia / Jamaica / Democratic Republic of the Congo", type: "Confederation" },
  { number: "519", name: "Suriname-Bolivia / Iraq CON", team: "Suriname / Bolivia / Iraq", type: "Confederation" },
  { number: "520", name: "Morten Hjulmand CON", team: "Denmark", type: "Confederation", persons: ["Morten Hjulmand"] },
  { number: "521", name: "Pierre-Emile Hojbjerg CON", team: "Denmark", type: "Confederation", persons: ["Pierre-Emile Hojbjerg"] },
  { number: "522", name: "Christian Eriksen CON", team: "Denmark", type: "Confederation", persons: ["Christian Eriksen"] },
  { number: "523", name: "Mikkel Damsgaard CON", team: "Denmark", type: "Confederation", persons: ["Mikkel Damsgaard"] },
  { number: "524", name: "Rasmus Hojlund CON", team: "Denmark", type: "Confederation", persons: ["Rasmus Hojlund"] },
  { number: "525", name: "Gianluigi Donnarumma CON", team: "Italy", type: "Confederation", persons: ["Gianluigi Donnarumma"] },
  { number: "526", name: "Alessandro Bastoni CON", team: "Italy", type: "Confederation", persons: ["Alessandro Bastoni"] },
  { number: "527", name: "Sandro Tonali CON", team: "Italy", type: "Confederation", persons: ["Sandro Tonali"] },
  { number: "528", name: "Nicolo Barella CON", team: "Italy", type: "Confederation", persons: ["Nicolo Barella"] },
  { number: "529", name: "Moise Kean CON", team: "Italy", type: "Confederation", persons: ["Moise Kean"] },
  { number: "530", name: "Andre Blake CON", team: "Jamaica", type: "Confederation", persons: ["Andre Blake"] },
  { number: "531", name: "Ethan Pinnock CON", team: "Jamaica", type: "Confederation", persons: ["Ethan Pinnock"] },
  { number: "532", name: "Demarai Gray CON", team: "Jamaica", type: "Confederation", persons: ["Demarai Gray"] },
  { number: "533", name: "Leon Bailey CON", team: "Jamaica", type: "Confederation", persons: ["Leon Bailey"] },
  { number: "534", name: "Shamar Nicholson CON", team: "Jamaica", type: "Confederation", persons: ["Shamar Nicholson"] },
  { number: "535", name: "Matty Cash CON", team: "Poland", type: "Confederation", persons: ["Matty Cash"] },
  { number: "536", name: "Jakub Kiwior CON", team: "Poland", type: "Confederation", persons: ["Jakub Kiwior"] },
  { number: "537", name: "Piotr Zielinski CON", team: "Poland", type: "Confederation", persons: ["Piotr Zielinski"] },
  { number: "538", name: "Sebastian Szymanski CON", team: "Poland", type: "Confederation", persons: ["Sebastian Szymanski"] },
  { number: "539", name: "Robert Lewandowski CON", team: "Poland", type: "Confederation", persons: ["Robert Lewandowski"] },
  { number: "540", name: "Isak Hien CON", team: "Sweden", type: "Confederation", persons: ["Isak Hien"] },
  { number: "541", name: "Dejan Kulusevski CON", team: "Sweden", type: "Confederation", persons: ["Dejan Kulusevski"] },
  { number: "542", name: "Anthony Elanga CON", team: "Sweden", type: "Confederation", persons: ["Anthony Elanga"] },
  { number: "543", name: "Viktor Gyokeres CON", team: "Sweden", type: "Confederation", persons: ["Viktor Gyokeres"] },
  { number: "544", name: "Alexander Isak CON", team: "Sweden", type: "Confederation", persons: ["Alexander Isak"] },
  { number: "545", name: "Caglar Soyuncu CON", team: "Turkey", type: "Confederation", persons: ["Caglar Soyuncu"] },
  { number: "546", name: "Hakan Calhanoglu CON", team: "Turkey", type: "Confederation", persons: ["Hakan Calhanoglu"] },
  { number: "547", name: "Arda Guler CON", team: "Turkey", type: "Confederation", persons: ["Arda Guler"] },
  { number: "548", name: "Kenan Yildiz CON", team: "Turkey", type: "Confederation", persons: ["Kenan Yildiz"] },
  { number: "549", name: "Kerem Akturkoglu CON", team: "Turkey", type: "Confederation", persons: ["Kerem Akturkoglu"] },

  // Team Keeper (TK) subset (550-558)
  { number: "550", name: "Emiliano Martinez TK", team: "Argentina", type: "Team Keeper", persons: ["Emiliano Martinez"] },
  { number: "551", name: "Thibaut Courtois TK", team: "Belgium", type: "Team Keeper", persons: ["Thibaut Courtois"] },
  { number: "552", name: "Alisson TK", team: "Brazil", type: "Team Keeper", persons: ["Alisson"] },
  { number: "553", name: "Mike Maignan TK", team: "France", type: "Team Keeper", persons: ["Mike Maignan"] },
  { number: "554", name: "Junnosuke Suzuki TK", team: "Japan", type: "Team Keeper", persons: ["Junnosuke Suzuki"] },
  { number: "555", name: "Yassine Bounou TK", team: "Morocco", type: "Team Keeper", persons: ["Yassine Bounou"] },
  { number: "556", name: "Diogo Costa TK", team: "Portugal", type: "Team Keeper", persons: ["Diogo Costa"] },
  { number: "557", name: "Unai Simon TK", team: "Spain", type: "Team Keeper", persons: ["Unai Simon"] },
  { number: "558", name: "Gregor Kobel TK", team: "Switzerland", type: "Team Keeper", persons: ["Gregor Kobel"] },

  // Defender (DR) subset (559-567)
  { number: "559", name: "Eder Militao DR", team: "Brazil", type: "Defender", persons: ["Eder Militao"] },
  { number: "560", name: "Alphonso Davies DR", team: "Canada", type: "Defender", persons: ["Alphonso Davies"] },
  { number: "561", name: "William Saliba DR", team: "France", type: "Defender", persons: ["William Saliba"] },
  { number: "562", name: "Antonio Rudiger DR", team: "Germany", type: "Defender", persons: ["Antonio Rudiger"] },
  { number: "563", name: "Min-jae Kim DR", team: "Korea Republic", type: "Defender", persons: ["Min-jae Kim"] },
  { number: "564", name: "Achraf Hakimi DR", team: "Morocco", type: "Defender", persons: ["Achraf Hakimi"] },
  { number: "565", name: "Virgil van Dijk DR", team: "Netherlands", type: "Defender", persons: ["Virgil van Dijk"] },
  { number: "566", name: "Nuno Mendes DR", team: "Portugal", type: "Defender", persons: ["Nuno Mendes"] },
  { number: "567", name: "Dean Huijsen DR", team: "Spain", type: "Defender", persons: ["Dean Huijsen"] },

  // Midfielder (MM) subset (568-585)
  { number: "568", name: "Enzo Fernandez MM", team: "Argentina", type: "Midfielder", persons: ["Enzo Fernandez"] },
  { number: "569", name: "Kevin De Bruyne MM", team: "Belgium", type: "Midfielder", persons: ["Kevin De Bruyne"] },
  { number: "570", name: "Casemiro MM", team: "Brazil", type: "Midfielder", persons: ["Casemiro"] },
  { number: "571", name: "Luka Modric MM", team: "Croatia", type: "Midfielder", persons: ["Luka Modric"] },
  { number: "572", name: "Moises Caicedo MM", team: "Ecuador", type: "Midfielder", persons: ["Moises Caicedo"] },
  { number: "573", name: "Jude Bellingham MM", team: "England", type: "Midfielder", persons: ["Jude Bellingham"] },
  { number: "574", name: "Aurelien Tchouameni MM", team: "France", type: "Midfielder", persons: ["Aurelien Tchouameni"] },
  { number: "575", name: "Florian Wirtz MM", team: "Germany", type: "Midfielder", persons: ["Florian Wirtz"] },
  { number: "576", name: "Sofyan Amrabat MM", team: "Morocco", type: "Midfielder", persons: ["Sofyan Amrabat"] },
  { number: "577", name: "Tijjani Reijnders MM", team: "Netherlands", type: "Midfielder", persons: ["Tijjani Reijnders"] },
  { number: "578", name: "Martin Odegaard MM", team: "Norway", type: "Midfielder", persons: ["Martin Odegaard"] },
  { number: "579", name: "Vitinha MM", team: "Portugal", type: "Midfielder", persons: ["Vitinha"] },
  { number: "580", name: "Scott McTominay MM", team: "Scotland", type: "Midfielder", persons: ["Scott McTominay"] },
  { number: "581", name: "Rodri MM", team: "Spain", type: "Midfielder", persons: ["Rodri"] },
  { number: "582", name: "Pedri MM", team: "Spain", type: "Midfielder", persons: ["Pedri"] },
  { number: "583", name: "Granit Xhaka MM", team: "Switzerland", type: "Midfielder", persons: ["Granit Xhaka"] },
  { number: "584", name: "Tyler Adams MM", team: "USA", type: "Midfielder", persons: ["Tyler Adams"] },
  { number: "585", name: "Federico Valverde MM", team: "Uruguay", type: "Midfielder", persons: ["Federico Valverde"] },

  // Goal Machine (GM) subset (586-607)
  { number: "586", name: "Julian Alvarez GM", team: "Argentina", type: "Goal Machine", persons: ["Julian Alvarez"] },
  { number: "587", name: "Romelu Lukaku GM", team: "Belgium", type: "Goal Machine", persons: ["Romelu Lukaku"] },
  { number: "588", name: "Raphinha GM", team: "Brazil", type: "Goal Machine", persons: ["Raphinha"] },
  { number: "589", name: "Jonathan David GM", team: "Canada", type: "Goal Machine", persons: ["Jonathan David"] },
  { number: "590", name: "Luis Diaz GM", team: "Colombia", type: "Goal Machine", persons: ["Luis Diaz"] },
  { number: "591", name: "Andrej Kramaric GM", team: "Croatia", type: "Goal Machine", persons: ["Andrej Kramaric"] },
  { number: "592", name: "Enner Valencia GM", team: "Ecuador", type: "Goal Machine", persons: ["Enner Valencia"] },
  { number: "593", name: "Omar Marmoush GM", team: "Egypt", type: "Goal Machine", persons: ["Omar Marmoush"] },
  { number: "594", name: "Marcus Rashford GM", team: "England", type: "Goal Machine", persons: ["Marcus Rashford"] },
  { number: "595", name: "Randal Kolo Muani GM", team: "France", type: "Goal Machine", persons: ["Randal Kolo Muani"] },
  { number: "596", name: "Kai Havertz GM", team: "Germany", type: "Goal Machine", persons: ["Kai Havertz"] },
  { number: "597", name: "Sebastien Haller GM", team: "Cote D'Ivoire", type: "Goal Machine", persons: ["Sebastien Haller"] },
  { number: "598", name: "Raul Jimenez GM", team: "Mexico", type: "Goal Machine", persons: ["Raul Jimenez"] },
  { number: "599", name: "Youssef En-Nesyri GM", team: "Morocco", type: "Goal Machine", persons: ["Youssef En-Nesyri"] },
  { number: "600", name: "Cody Gakpo GM", team: "Netherlands", type: "Goal Machine", persons: ["Cody Gakpo"] },
  { number: "601", name: "Chris Wood GM", team: "New Zealand", type: "Goal Machine", persons: ["Chris Wood"] },
  { number: "602", name: "Alexander Sorloth GM", team: "Norway", type: "Goal Machine", persons: ["Alexander Sorloth"] },
  { number: "603", name: "Nicolas Jackson GM", team: "Senegal", type: "Goal Machine", persons: ["Nicolas Jackson"] },
  { number: "604", name: "Mikel Oyarzabal GM", team: "Spain", type: "Goal Machine", persons: ["Mikel Oyarzabal"] },
  { number: "605", name: "Breel Embolo GM", team: "Switzerland", type: "Goal Machine", persons: ["Breel Embolo"] },
  { number: "606", name: "Christian Pulisic GM", team: "USA", type: "Goal Machine", persons: ["Christian Pulisic"] },
  { number: "607", name: "Darwin Nunez GM", team: "Uruguay", type: "Goal Machine", persons: ["Darwin Nunez"] },

  // Midfielder Rising (MR) subset (608-624)
  { number: "608", name: "Nico Paz MR", team: "Argentina", type: "Midfielder Rising", persons: ["Nico Paz"] },
  { number: "609", name: "Franco Mastantuono MR", team: "Argentina", type: "Midfielder Rising", persons: ["Franco Mastantuono"] },
  { number: "610", name: "Zeno Debast MR", team: "Belgium", type: "Midfielder Rising", persons: ["Zeno Debast"] },
  { number: "611", name: "Wesley MR", team: "Brazil", type: "Midfielder Rising", persons: ["Wesley"] },
  { number: "612", name: "Estêvão MR", team: "Brazil", type: "Midfielder Rising", persons: ["Estêvão"] },
  { number: "613", name: "Petar Sucic MR", team: "Croatia", type: "Midfielder Rising", persons: ["Petar Sucic"] },
  { number: "614", name: "Kendry Paez MR", team: "Ecuador", type: "Midfielder Rising", persons: ["Kendry Paez"] },
  { number: "615", name: "Morgan Rogers MR", team: "England", type: "Midfielder Rising", persons: ["Morgan Rogers"] },
  { number: "616", name: "Desire Doue MR", team: "France", type: "Midfielder Rising", persons: ["Desire Doue"] },
  { number: "617", name: "Bradley Barcola MR", team: "France", type: "Midfielder Rising", persons: ["Bradley Barcola"] },
  { number: "618", name: "Nick Woltemade MR", team: "Germany", type: "Midfielder Rising", persons: ["Nick Woltemade"] },
  { number: "619", name: "Xavi Simons MR", team: "Netherlands", type: "Midfielder Rising", persons: ["Xavi Simons"] },
  { number: "620", name: "Andreas Schjelderup MR", team: "Norway", type: "Midfielder Rising", persons: ["Andreas Schjelderup"] },
  { number: "621", name: "Diego Gomez MR", team: "Paraguay", type: "Midfielder Rising", persons: ["Diego Gomez"] },
  { number: "622", name: "Joao Neves MR", team: "Portugal", type: "Midfielder Rising", persons: ["Joao Neves"] },
  { number: "623", name: "Pau Cubarsi MR", team: "Spain", type: "Midfielder Rising", persons: ["Pau Cubarsi"] },
  { number: "624", name: "Official Emblem", team: "FIFA", type: "Emblem" },

  // Special subsets (625-648)
  { number: "625", name: "Maple MAS", team: "Canada", type: "Special" },
  { number: "626", name: "Clutch MAS", team: "USA", type: "Special" },
  { number: "627", name: "Zayu MAS", team: "Japan", type: "Special" },
  { number: "628", name: "Molina / Martínez / Romero E22", team: "Argentina", type: "Emerald 22", persons: ["Molina", "Martínez", "Romero"] },
  { number: "629", name: "De Paul / Mac Allister / Fernández E22", team: "Argentina", type: "Emerald 22", persons: ["De Paul", "Mac Allister", "Fernández"] },
  { number: "630", name: "Martínez / Messi / Álvarez E22", team: "Argentina", type: "Emerald 22", persons: ["Martínez", "Messi", "Álvarez"] },
  { number: "631", name: "Sander Berge NE, SS", team: "Norway", type: "National Elite", persons: ["Sander Berge"] },
  { number: "632", name: "Thelo Aasgaard NE, MR", team: "Norway", type: "National Elite", persons: ["Thelo Aasgaard"] },
  { number: "633", name: "Erling Haaland NE, GIA", team: "Norway", type: "National Elite", persons: ["Erling Haaland"] },
  { number: "634", name: "Martin Ødegaard NE, SS", team: "Norway", type: "National Elite", persons: ["Martin Ødegaard"] },
  { number: "635", name: "Antonio Nusa NE, MR", team: "Norway", type: "National Elite", persons: ["Antonio Nusa"] },
  { number: "636", name: "Erling Haaland NE, GIA", team: "Norway", type: "National Elite", persons: ["Erling Haaland"] },
  { number: "637", name: "Alexander Sorloth NE, SS", team: "Norway", type: "National Elite", persons: ["Alexander Sorloth"] },
  { number: "638", name: "Oscar Bobb NE, MR", team: "Norway", type: "National Elite", persons: ["Oscar Bobb"] },
  { number: "639", name: "Erling Haaland NE, GIA", team: "Norway", type: "National Elite", persons: ["Erling Haaland"] },
  { number: "640", name: "Kasper Schmeichel NE, SS", team: "Denmark", type: "National Elite", persons: ["Kasper Schmeichel"] },
  { number: "641", name: "Andreas Christensen NE, SS", team: "Denmark", type: "National Elite", persons: ["Andreas Christensen"] },
  { number: "642", name: "Rasmus Hojlund NE, SS", team: "Denmark", type: "National Elite", persons: ["Rasmus Hojlund"] },
  { number: "643", name: "Patrick Dorgu NE, MR", team: "Denmark", type: "National Elite", persons: ["Patrick Dorgu"] },
  { number: "644", name: "Victor Froholdt NE, MR", team: "Denmark", type: "National Elite", persons: ["Victor Froholdt"] },
  { number: "645", name: "Viktor Gyökeres NE, SS", team: "Sweden", type: "National Elite", persons: ["Viktor Gyökeres"] },
  { number: "646", name: "Alexander Isak NE, SS", team: "Sweden", type: "National Elite", persons: ["Alexander Isak"] },
  { number: "647", name: "Lucas Bergvall NE, MR", team: "Sweden", type: "National Elite", persons: ["Lucas Bergvall"] },
  { number: "648", name: "Roony Bardghji NE, MR", team: "Sweden", type: "National Elite", persons: ["Roony Bardghji"] },
];

async function main() {
  console.log(`Seeding: ${SET_NAME} (${ALL_CARDS.length} cards)`);

  const universeId = await builder.getOrCreateUniverse("Sports");
  const manufacturerId = await builder.getOrCreateManufacturer("Panini");
  const franchiseId = await builder.getOrCreateFranchise("Football (Soccer)", universeId);
  const brandId = await builder.getOrCreateBrand("Adrenalyn XL", manufacturerId);
  const seriesId = await builder.getOrCreateSeries("World Cup 2026", franchiseId, brandId);
  const set = await builder.getOrCreateSet({
    id: SET_ID,
    name: SET_NAME,
    seriesId,
    printedTotal: ALL_CARDS.length,
  });
  const basePrintingId = await builder.getOrCreatePrinting("Base");

  let created = 0;
  let skipped = 0;
  const t0 = Date.now();

  for (const [i, row] of ALL_CARDS.entries()) {
    const cardId = `${SET_ID}-${String(row.number).toLowerCase().replace(/[^a-z0-9]/g, "")}`;
    const existing = await prisma.card.findUnique({ where: { id: cardId } });
    if (existing) { skipped++; continue; }

    const personIds: string[] = [];
    if (row.persons) {
      for (const name of row.persons) personIds.push(await builder.getOrCreatePerson(name));
    }

    await prisma.card.create({
      data: {
        id: cardId,
        name: row.name,
        number: String(row.number),
        setId: set.id,
        supertype: row.type ?? "Base",
        persons: personIds.length > 0 ? { connect: personIds.map((id) => ({ id })) } : undefined,
      },
    });

    created++;
    if ((i + 1) % 50 === 0) console.log(`  [${i + 1}/${ALL_CARDS.length}] created=${created}`);
  }

  console.log(`Done. Created ${created} cards, skipped ${skipped}. Set: ${SET_NAME} (${(Date.now() - t0) / 1000}s)`);
}

main()
  .catch((e) => { console.error(e); process.exitCode = 1; })
  .finally(async () => { await prisma.$disconnect(); });