import { prisma } from "../ingestion/engine/prisma";
import { builder } from "../ingestion/engine/builder";

/**
 * Seeds the Panini Adrenalyn XL FIFA 365 2025 trading card set.
 * Comprehensive checklist with all subsets: World Top Clubs, Golden Baller/Invincible,
 * Road to World Cup 26, Elite Cut, Fans' Favourite, Momentum, Rising Star, Club 99,
 * Star Signings, Excellence Box, Limited Edition, and more.
 */
const SET_ID = "panini-adrenalyn-fifa-365-2025";
const SET_NAME = "Adrenalyn XL FIFA 365 2025";

interface CardRow {
  number: string;
  name: string;
  team: string;
  subset?: string;
  type?: string;
  persons?: string[];
}

const ALL_CARDS: CardRow[] = [
  // Golden Baller / Invincible (9 cards)
  { number: "GOL1", name: "Mohamed Salah", team: "Liverpool", subset: "Golden Baller", persons: ["Mohamed Salah"] },
  { number: "GOL2", name: "Achraf Hakimi", team: "Paris Saint-Germain", subset: "Golden Baller", persons: ["Achraf Hakimi"] },
  { number: "GOL3", name: "Khvicha Kvaratskhelia", team: "Paris Saint-Germain", subset: "Golden Baller", persons: ["Khvicha Kvaratskhelia"] },
  { number: "GOL4", name: "Alessandro Bastoni", team: "FC Internazionale Milano", subset: "Golden Baller", persons: ["Alessandro Bastoni"] },
  { number: "GOL5", name: "Emiliano Martínez", team: "Aston Villa", subset: "Invincible", persons: ["Emiliano Martínez"] },
  { number: "GOL5", name: "Jude Bellingham", team: "Real Madrid CF", subset: "Invincible", persons: ["Jude Bellingham"] },
  { number: "GOL5", name: "Lamine Yamal", team: "FC Barcelona", subset: "Invincible", persons: ["Lamine Yamal"] },
  { number: "GOL5", name: "Kylian Mbappé", team: "Real Madrid CF", subset: "Invincible", persons: ["Kylian Mbappé"] },
  { number: "GOL6", name: "Cristiano Ronaldo", team: "Al-Nassr FC", subset: "Golden Baller", persons: ["Cristiano Ronaldo"] },
  { number: "GOL7", name: "Julián Álvarez", team: "Atlético de Madrid", subset: "Golden Baller", persons: ["Julián Álvarez"] },
  { number: "GOL8", name: "Trent Alexander-Arnold", team: "Real Madrid CF", subset: "Golden Baller", persons: ["Trent Alexander-Arnold"] },
  { number: "GOL9", name: "Vinicius Jr.", team: "Real Madrid CF", subset: "Golden Baller", persons: ["Vinicius Jr"] },

  // World Top Clubs - Botafogo (18 cards)
  { number: "BOT1", name: "Club Badge", team: "Botafogo", subset: "World Top Clubs", type: "Club Badge" },
  { number: "BOT2", name: "John Victor", team: "Botafogo", subset: "World Top Clubs", persons: ["John Victor"] },
  { number: "BOT3", name: "Vitinho", team: "Botafogo", subset: "World Top Clubs", persons: ["Vitinho"] },
  { number: "BOT4", name: "Alex Telles", team: "Botafogo", subset: "World Top Clubs", persons: ["Alex Telles"] },
  { number: "BOT5", name: "Cuiabano", team: "Botafogo", subset: "World Top Clubs", persons: ["Cuiabano"] },
  { number: "BOT6", name: "Jair Cunha", team: "Botafogo", subset: "World Top Clubs", persons: ["Jair Cunha"] },
  { number: "BOT7", name: "Alexander Barboza", team: "Botafogo", subset: "World Top Clubs", type: "Titan", persons: ["Alexander Barboza"] },
  { number: "BOT8", name: "Danilo Barbosa", team: "Botafogo", subset: "World Top Clubs", persons: ["Danilo Barbosa"] },
  { number: "BOT9", name: "Gregore", team: "Botafogo", subset: "World Top Clubs", persons: ["Gregore"] },
  { number: "BOT10", name: "Marlon Freitas", team: "Botafogo", subset: "World Top Clubs", persons: ["Marlon Freitas"] },
  { number: "BOT11", name: "Santiago Rodríguez", team: "Botafogo", subset: "World Top Clubs", persons: ["Santiago Rodríguez"] },
  { number: "BOT12", name: "Jefferson Savarino", team: "Botafogo", subset: "World Top Clubs", type: "Magician", persons: ["Jefferson Savarino"] },
  { number: "BOT13", name: "Artur", team: "Botafogo", subset: "World Top Clubs", persons: ["Artur"] },
  { number: "BOT14", name: "Joaquín Correa", team: "Botafogo", subset: "World Top Clubs", persons: ["Joaquín Correa"] },
  { number: "BOT15", name: "Nathan Fernandes", team: "Botafogo", subset: "World Top Clubs", persons: ["Nathan Fernandes"] },
  { number: "BOT16", name: "Gonzalo Mastriani", team: "Botafogo", subset: "World Top Clubs", persons: ["Gonzalo Mastriani"] },
  { number: "BOT17", name: "Arthur Cabral", team: "Botafogo", subset: "World Top Clubs", persons: ["Arthur Cabral"] },
  { number: "BOT18", name: "Igor Jesus", team: "Botafogo", subset: "World Top Clubs", type: "Dominator", persons: ["Igor Jesus"] },

  // World Top Clubs - Liverpool (18 cards)
  { number: "LIV1", name: "Club Badge", team: "Liverpool", subset: "World Top Clubs", type: "Club Badge" },
  { number: "LIV2", name: "Alisson", team: "Liverpool", subset: "World Top Clubs", persons: ["Alisson"] },
  { number: "LIV3", name: "Conor Bradley", team: "Liverpool", subset: "World Top Clubs", persons: ["Conor Bradley"] },
  { number: "LIV4", name: "Andrew Robertson", team: "Liverpool", subset: "World Top Clubs", persons: ["Andrew Robertson"] },
  { number: "LIV5", name: "Milos Kerkez", team: "Liverpool", subset: "World Top Clubs", persons: ["Milos Kerkez"] },
  { number: "LIV6", name: "Ibrahima Konaté", team: "Liverpool", subset: "World Top Clubs", persons: ["Ibrahima Konaté"] },
  { number: "LIV7", name: "Virgil van Dijk", team: "Liverpool", subset: "World Top Clubs", type: "Titan", persons: ["Virgil van Dijk"] },
  { number: "LIV8", name: "Jeremie Frimpong", team: "Liverpool", subset: "World Top Clubs", persons: ["Jeremie Frimpong"] },
  { number: "LIV9", name: "Ryan Gravenberch", team: "Liverpool", subset: "World Top Clubs", persons: ["Ryan Gravenberch"] },
  { number: "LIV10", name: "Alexis Mac Allister", team: "Liverpool", subset: "World Top Clubs", persons: ["Alexis Mac Allister"] },
  { number: "LIV11", name: "Curtis Jones", team: "Liverpool", subset: "World Top Clubs", persons: ["Curtis Jones"] },
  { number: "LIV12", name: "Dominik Szoboszlai", team: "Liverpool", subset: "World Top Clubs", type: "Magician", persons: ["Dominik Szoboszlai"] },
  { number: "LIV13", name: "Florian Wirtz", team: "Liverpool", subset: "World Top Clubs", persons: ["Florian Wirtz"] },
  { number: "LIV14", name: "Harvey Elliott", team: "Liverpool", subset: "World Top Clubs", persons: ["Harvey Elliott"] },
  { number: "LIV15", name: "Luis Díaz", team: "Liverpool", subset: "World Top Clubs", persons: ["Luis Díaz"] },
  { number: "LIV16", name: "Darwin Núñez", team: "Liverpool", subset: "World Top Clubs", persons: ["Darwin Núñez"] },
  { number: "LIV17", name: "Cody Gakpo", team: "Liverpool", subset: "World Top Clubs", persons: ["Cody Gakpo"] },
  { number: "LIV18", name: "Mohamed Salah", team: "Liverpool", subset: "World Top Clubs", type: "Dominator", persons: ["Mohamed Salah"] },

  // World Top Clubs - Olympique de Marseille (18 cards)
  { number: "OLM1", name: "Club Badge", team: "Olympique de Marseille", subset: "World Top Clubs", type: "Club Badge" },
  { number: "OLM2", name: "Gerónimo Rulli", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Gerónimo Rulli"] },
  { number: "OLM3", name: "Amir Murillo", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Amir Murillo"] },
  { number: "OLM4", name: "Quentin Merlin", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Quentin Merlin"] },
  { number: "OLM5", name: "Ulisses García", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Ulisses García"] },
  { number: "OLM6", name: "Derek Cornelius", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Derek Cornelius"] },
  { number: "OLM7", name: "Leonardo Balerdi", team: "Olympique de Marseille", subset: "World Top Clubs", type: "Titan", persons: ["Leonardo Balerdi"] },
  { number: "OLM8", name: "Ángel Gomes", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Ángel Gomes"] },
  { number: "OLM9", name: "Valentin Rongier", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Valentin Rongier"] },
  { number: "OLM10", name: "Geoffrey Kondogbia", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Geoffrey Kondogbia"] },
  { number: "OLM11", name: "Pierre-Emile Højbjerg", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Pierre-Emile Højbjerg"] },
  { number: "OLM12", name: "Amine Harit", team: "Olympique de Marseille", subset: "World Top Clubs", type: "Magician", persons: ["Amine Harit"] },
  { number: "OLM13", name: "Adrien Rabiot", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Adrien Rabiot"] },
  { number: "OLM14", name: "Bilal Nadir", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Bilal Nadir"] },
  { number: "OLM15", name: "Jonathan Rowe", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Jonathan Rowe"] },
  { number: "OLM16", name: "Mason Greenwood", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Mason Greenwood"] },
  { number: "OLM17", name: "Neal Maupay", team: "Olympique de Marseille", subset: "World Top Clubs", persons: ["Neal Maupay"] },
  { number: "OLM18", name: "Amine Gouiri", team: "Olympique de Marseille", subset: "World Top Clubs", type: "Dominator", persons: ["Amine Gouiri"] },

  // World Top Clubs - Paris Saint-Germain (18 cards)
  { number: "PAS1", name: "Europe's Elite", team: "Paris Saint-Germain", subset: "World Top Clubs", type: "Special" },
  { number: "PAS2", name: "Gianluigi Donnarumma", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Gianluigi Donnarumma"] },
  { number: "PAS3", name: "Ashraf Hakimi", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Ashraf Hakimi"] },
  { number: "PAS4", name: "Nuno Mendes", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Nuno Mendes"] },
  { number: "PAS5", name: "Lucas Hernández", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Lucas Hernández"] },
  { number: "PAS6", name: "Willian Pacho", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Willian Pacho"] },
  { number: "PAS7", name: "Marquinhos", team: "Paris Saint-Germain", subset: "World Top Clubs", type: "Titan", persons: ["Marquinhos"] },
  { number: "PAS8", name: "Lucas Beraldo", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Lucas Beraldo"] },
  { number: "PAS9", name: "João Neves", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["João Neves"] },
  { number: "PAS10", name: "Warren Zaïre-Emery", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Warren Zaïre-Emery"] },
  { number: "PAS11", name: "Vitinha", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Vitinha"] },
  { number: "PAS12", name: "Fabián Ruiz", team: "Paris Saint-Germain", subset: "World Top Clubs", type: "Magician", persons: ["Fabián Ruiz"] },
  { number: "PAS13", name: "Khvicha Kvaratskhelia", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Khvicha Kvaratskhelia"] },
  { number: "PAS14", name: "Kang-in Lee", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Kang-in Lee"] },
  { number: "PAS15", name: "Désiré Doué", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Désiré Doué"] },
  { number: "PAS16", name: "Bradley Barcola", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Bradley Barcola"] },
  { number: "PAS17", name: "Gonçalo Ramos", team: "Paris Saint-Germain", subset: "World Top Clubs", persons: ["Gonçalo Ramos"] },
  { number: "PAS18", name: "Ousmane Dembélé", team: "Paris Saint-Germain", subset: "World Top Clubs", type: "Dominator", persons: ["Ousmane Dembélé"] },

  // Continue with remaining clubs...
  // Bayer 04 Leverkusen (18 cards)
  { number: "BLE1", name: "Club Badge", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", type: "Club Badge" },
  { number: "BLE2", name: "Lukáš Hrádecký", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Lukáš Hrádecký"] },
  { number: "BLE3", name: "Mark Flekken", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Mark Flekken"] },
  { number: "BLE4", name: "Edmond Tapsoba", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Edmond Tapsoba"] },
  { number: "BLE5", name: "Arthur", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Arthur"] },
  { number: "BLE6", name: "Exequiel Palacios", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Exequiel Palacios"] },
  { number: "BLE7", name: "Piero Hincapié", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", type: "Titan", persons: ["Piero Hincapié"] },
  { number: "BLE8", name: "Robert Andrich", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Robert Andrich"] },
  { number: "BLE9", name: "Granit Xhaka", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Granit Xhaka"] },
  { number: "BLE10", name: "Aleix García", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Aleix García"] },
  { number: "BLE11", name: "Ibraim Maza", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Ibraim Maza"] },
  { number: "BLE12", name: "Alejandro Grimaldo", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", type: "Magician", persons: ["Alejandro Grimaldo"] },
  { number: "BLE13", name: "Jonas Hofmann", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Jonas Hofmann"] },
  { number: "BLE14", name: "Martin Terrier", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Martin Terrier"] },
  { number: "BLE15", name: "Amine Adli", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Amine Adli"] },
  { number: "BLE16", name: "Nathan Tella", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Nathan Tella"] },
  { number: "BLE17", name: "Victor Boniface", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", persons: ["Victor Boniface"] },
  { number: "BLE18", name: "Patrik Schick", team: "Bayer 04 Leverkusen", subset: "World Top Clubs", type: "Dominator", persons: ["Patrik Schick"] },

  // Eintracht Frankfurt (18 cards)
  { number: "EIN1", name: "Club Badge", team: "Eintracht Frankfurt", subset: "World Top Clubs", type: "Club Badge" },
  { number: "EIN2", name: "Kevin Trapp", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Kevin Trapp"] },
  { number: "EIN3", name: "Rasmus Kristensen", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Rasmus Kristensen"] },
  { number: "EIN4", name: "Nathaniel Brown", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Nathaniel Brown"] },
  { number: "EIN5", name: "Arthur Theate", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Arthur Theate"] },
  { number: "EIN6", name: "Tuta", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Tuta"] },
  { number: "EIN7", name: "Robin Koch", team: "Eintracht Frankfurt", subset: "World Top Clubs", type: "Titan", persons: ["Robin Koch"] },
  { number: "EIN8", name: "Nnamdi Collins", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Nnamdi Collins"] },
  { number: "EIN9", name: "Oscar Højlund", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Oscar Højlund"] },
  { number: "EIN10", name: "Hugo Larsson", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Hugo Larsson"] },
  { number: "EIN11", name: "Ellyes Skhiri", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Ellyes Skhiri"] },
  { number: "EIN12", name: "Mario Götze", team: "Eintracht Frankfurt", subset: "World Top Clubs", type: "Magician", persons: ["Mario Götze"] },
  { number: "EIN13", name: "Farès Chaïbi", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Farès Chaïbi"] },
  { number: "EIN14", name: "Can Uzun", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Can Uzun"] },
  { number: "EIN15", name: "Ansgar Knauff", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Ansgar Knauff"] },
  { number: "EIN16", name: "Jean Mattéo Bahoya", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Jean Mattéo Bahoya"] },
  { number: "EIN17", name: "Michy Batshuayi", team: "Eintracht Frankfurt", subset: "World Top Clubs", persons: ["Michy Batshuayi"] },
  { number: "EIN18", name: "Jonathan Burkardt", team: "Eintracht Frankfurt", subset: "World Top Clubs", type: "Dominator", persons: ["Jonathan Burkardt"] },

  // Olympiacos FC (18 cards)
  { number: "OLY1", name: "Club Badge", team: "Olympiacos FC", subset: "World Top Clubs", type: "Club Badge" },
  { number: "OLY2", name: "Konstantinos Tzolakis", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Konstantinos Tzolakis"] },
  { number: "OLY3", name: "Alexandros Paschalakis", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Alexandros Paschalakis"] },
  { number: "OLY4", name: "Rodinei", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Rodinei"] },
  { number: "OLY5", name: "Francisco Ortega", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Francisco Ortega"] },
  { number: "OLY6", name: "Costinha", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Costinha"] },
  { number: "OLY7", name: "Panagiotis Retsos", team: "Olympiacos FC", subset: "World Top Clubs", type: "Titan", persons: ["Panagiotis Retsos"] },
  { number: "OLY8", name: "Bruno Onyemaechi", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Bruno Onyemaechi"] },
  { number: "OLY9", name: "Giulian Biancone", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Giulian Biancone"] },
  { number: "OLY10", name: "Lorenzo Pirola", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Lorenzo Pirola"] },
  { number: "OLY11", name: "Dani García", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Dani García"] },
  { number: "OLY12", name: "Chiquinho", team: "Olympiacos FC", subset: "World Top Clubs", type: "Magician", persons: ["Chiquinho"] },
  { number: "OLY13", name: "Santiago Hezze", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Santiago Hezze"] },
  { number: "OLY14", name: "Christos Mouzakitis", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Christos Mouzakitis"] },
  { number: "OLY15", name: "Rémy Cabella", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Rémy Cabella"] },
  { number: "OLY16", name: "Gelson Martins", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Gelson Martins"] },
  { number: "OLY17", name: "Roman Yaremchuk", team: "Olympiacos FC", subset: "World Top Clubs", persons: ["Roman Yaremchuk"] },
  { number: "OLY18", name: "Ayoub El Kaabi", team: "Olympiacos FC", subset: "World Top Clubs", type: "Dominator", persons: ["Ayoub El Kaabi"] },

  // FC Internazionale Milano (18 cards)
  { number: "INT1", name: "Club Badge", team: "FC Internazionale Milano", subset: "World Top Clubs", type: "Club Badge" },
  { number: "INT2", name: "Yann Sommer", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Yann Sommer"] },
  { number: "INT3", name: "Alessandro Bastoni", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Alessandro Bastoni"] },
  { number: "INT4", name: "Benjamin Pavard", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Benjamin Pavard"] },
  { number: "INT5", name: "Stefan de Vrij", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Stefan de Vrij"] },
  { number: "INT6", name: "Yann Bisseck", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Yann Bisseck"] },
  { number: "INT7", name: "Francesco Acerbi", team: "FC Internazionale Milano", subset: "World Top Clubs", type: "Titan", persons: ["Francesco Acerbi"] },
  { number: "INT8", name: "Matteo Darmian", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Matteo Darmian"] },
  { number: "INT9", name: "Federico Dimarco", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Federico Dimarco"] },
  { number: "INT10", name: "Denzel Dumfries", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Denzel Dumfries"] },
  { number: "INT11", name: "Carlos Augusto", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Carlos Augusto"] },
  { number: "INT12", name: "Nicolò Barella", team: "FC Internazionale Milano", subset: "World Top Clubs", type: "Magician", persons: ["Nicolò Barella"] },
  { number: "INT13", name: "Hakan Çalhanoğlu", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Hakan Çalhanoğlu"] },
  { number: "INT14", name: "Henrikh Mkhitaryan", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Henrikh Mkhitaryan"] },
  { number: "INT15", name: "Luis Henrique", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Luis Henrique"] },
  { number: "INT16", name: "Mehdi Taremi", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Mehdi Taremi"] },
  { number: "INT17", name: "Marcus Thuram", team: "FC Internazionale Milano", subset: "World Top Clubs", persons: ["Marcus Thuram"] },
  { number: "INT18", name: "Lautaro Martínez", team: "FC Internazionale Milano", subset: "World Top Clubs", type: "Dominator", persons: ["Lautaro Martínez"] },

  // AC Milan (18 cards)
  { number: "MIL1", name: "Club Badge", team: "AC Milan", subset: "World Top Clubs", type: "Club Badge" },
  { number: "MIL2", name: "Mike Maignan", team: "AC Milan", subset: "World Top Clubs", persons: ["Mike Maignan"] },
  { number: "MIL3", name: "Emerson Royal", team: "AC Milan", subset: "World Top Clubs", persons: ["Emerson Royal"] },
  { number: "MIL4", name: "Theo Hernández", team: "AC Milan", subset: "World Top Clubs", persons: ["Theo Hernández"] },
  { number: "MIL5", name: "Álex Jiménez", team: "AC Milan", subset: "World Top Clubs", persons: ["Álex Jiménez"] },
  { number: "MIL6", name: "Fikayo Tomori", team: "AC Milan", subset: "World Top Clubs", persons: ["Fikayo Tomori"] },
  { number: "MIL7", name: "Strahinja Pavlovic", team: "AC Milan", subset: "World Top Clubs", type: "Titan", persons: ["Strahinja Pavlovic"] },
  { number: "MIL8", name: "Matteo Gabbia", team: "AC Milan", subset: "World Top Clubs", persons: ["Matteo Gabbia"] },
  { number: "MIL9", name: "Malick Thlaw", team: "AC Milan", subset: "World Top Clubs", persons: ["Malick Thlaw"] },
  { number: "MIL10", name: "Davide Bartesaghi", team: "AC Milan", subset: "World Top Clubs", persons: ["Davide Bartesaghi"] },
  { number: "MIL11", name: "Youssouf Fofana", team: "AC Milan", subset: "World Top Clubs", persons: ["Youssouf Fofana"] },
  { number: "MIL12", name: "Christian Pulisic", team: "AC Milan", subset: "World Top Clubs", type: "Magician", persons: ["Christian Pulisic"] },
  { number: "MIL13", name: "Ruben Loftus-Cheek", team: "AC Milan", subset: "World Top Clubs", persons: ["Ruben Loftus-Cheek"] },
  { number: "MIL14", name: "Samuel Chukwueze", team: "AC Milan", subset: "World Top Clubs", persons: ["Samuel Chukwueze"] },
  { number: "MIL15", name: "Francesco Camarda", team: "AC Milan", subset: "World Top Clubs", persons: ["Francesco Camarda"] },
  { number: "MIL16", name: "Rafael Leão", team: "AC Milan", subset: "World Top Clubs", persons: ["Rafael Leão"] },
  { number: "MIL17", name: "Luka Jović", team: "AC Milan", subset: "World Top Clubs", persons: ["Luka Jović"] },
  { number: "MIL18", name: "Santiago Giménez", team: "AC Milan", subset: "World Top Clubs", type: "Dominator", persons: ["Santiago Giménez"] },

  // AFC Ajax (18 cards)
  { number: "AJA1", name: "Club Badge", team: "AFC Ajax", subset: "World Top Clubs", type: "Club Badge" },
  { number: "AJA2", name: "Remko Pasveer", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Remko Pasveer"] },
  { number: "AJA3", name: "Anton Gaaei", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Anton Gaaei"] },
  { number: "AJA4", name: "Jorrel Hato", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Jorrel Hato"] },
  { number: "AJA5", name: "Josip Šutalo", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Josip Šutalo"] },
  { number: "AJA6", name: "Jorthy Mokio", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Jorthy Mokio"] },
  { number: "AJA7", name: "Youri Baas", team: "AFC Ajax", subset: "World Top Clubs", type: "Titan", persons: ["Youri Baas"] },
  { number: "AJA8", name: "Youri Regeer", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Youri Regeer"] },
  { number: "AJA9", name: "Kian Fitz-Jim", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Kian Fitz-Jim"] },
  { number: "AJA10", name: "Jordan Henderson", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Jordan Henderson"] },
  { number: "AJA11", name: "Steven Berghuis", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Steven Berghuis"] },
  { number: "AJA12", name: "Kenneth Taylor", team: "AFC Ajax", subset: "World Top Clubs", type: "Magician", persons: ["Kenneth Taylor"] },
  { number: "AJA13", name: "Davy Klaassen", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Davy Klaassen"] },
  { number: "AJA14", name: "Oliver Edvardsen", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Oliver Edvardsen"] },
  { number: "AJA15", name: "Mika Godts", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Mika Godts"] },
  { number: "AJA16", name: "Bertrand Traoré", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Bertrand Traoré"] },
  { number: "AJA17", name: "Brian Brobbey", team: "AFC Ajax", subset: "World Top Clubs", persons: ["Brian Brobbey"] },
  { number: "AJA18", name: "Wout Weghorst", team: "AFC Ajax", subset: "World Top Clubs", type: "Dominator", persons: ["Wout Weghorst"] },

  // PSV Eindhoven (18 cards)
  { number: "PSV1", name: "Club Badge", team: "PSV Eindhoven", subset: "World Top Clubs", type: "Club Badge" },
  { number: "PSV2", name: "Nick Olij", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Nick Olij"] },
  { number: "PSV3", name: "Adamo Nagalo", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Adamo Nagalo"] },
  { number: "PSV4", name: "Mauro Junior", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Mauro Junior"] },
  { number: "PSV5", name: "Sergiño Dest", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Sergiño Dest"] },
  { number: "PSV6", name: "Armando Obispo", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Armando Obispo"] },
  { number: "PSV7", name: "Ryan Flamingo", team: "PSV Eindhoven", subset: "World Top Clubs", type: "Titan", persons: ["Ryan Flamingo"] },
  { number: "PSV8", name: "Yarek Gasiorowski", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Yarek Gasiorowski"] },
  { number: "PSV9", name: "Tygo Land", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Tygo Land"] },
  { number: "PSV10", name: "Jerdy Schouten", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Jerdy Schouten"] },
  { number: "PSV11", name: "Joey Veerman", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Joey Veerman"] },
  { number: "PSV12", name: "Ismael Saibari", team: "PSV Eindhoven", subset: "World Top Clubs", type: "Magician", persons: ["Ismael Saibari"] },
  { number: "PSV13", name: "Guus Til", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Guus Til"] },
  { number: "PSV14", name: "Ivan Perišić", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Ivan Perišić"] },
  { number: "PSV15", name: "Ruben Van Bommel", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Ruben Van Bommel"] },
  { number: "PSV16", name: "Alassane Pléa", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Alassane Pléa"] },
  { number: "PSV17", name: "Couhaib Driouech", team: "PSV Eindhoven", subset: "World Top Clubs", persons: ["Couhaib Driouech"] },
  { number: "PSV18", name: "Ricardo Pepi", team: "PSV Eindhoven", subset: "World Top Clubs", type: "Dominator", persons: ["Ricardo Pepi"] },

  // Sporting Clube de Portugal (18 cards)
  { number: "SPO1", name: "Club Badge", team: "Sporting Clube de Portugal", subset: "World Top Clubs", type: "Club Badge" },
  { number: "SPO2", name: "Rui Silva", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Rui Silva"] },
  { number: "SPO3", name: "Zeno Debast", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Zeno Debast"] },
  { number: "SPO4", name: "Ousmane Diomande", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Ousmane Diomande"] },
  { number: "SPO5", name: "Matheus Reis", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Matheus Reis"] },
  { number: "SPO6", name: "Iván Fresneda", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Iván Fresneda"] },
  { number: "SPO7", name: "Gonçalo Inácio", team: "Sporting Clube de Portugal", subset: "World Top Clubs", type: "Titan", persons: ["Gonçalo Inácio"] },
  { number: "SPO8", name: "Eduardo Quaresma", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Eduardo Quaresma"] },
  { number: "SPO9", name: "Nuno Santos", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Nuno Santos"] },
  { number: "SPO10", name: "Morten Hjulmand", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Morten Hjulmand"] },
  { number: "SPO11", name: "Hidemasa Morita", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Hidemasa Morita"] },
  { number: "SPO12", name: "Daniel Bragança", team: "Sporting Clube de Portugal", subset: "World Top Clubs", type: "Magician", persons: ["Daniel Bragança"] },
  { number: "SPO13", name: "Maxi Araújo", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Maxi Araújo"] },
  { number: "SPO14", name: "Pedro Gonçalves", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Pedro Gonçalves"] },
  { number: "SPO15", name: "Geny Catamo", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Geny Catamo"] },
  { number: "SPO16", name: "Geovany Quenda", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Geovany Quenda"] },
  { number: "SPO17", name: "Trincão", team: "Sporting Clube de Portugal", subset: "World Top Clubs", persons: ["Trincão"] },
  { number: "SPO18", name: "Conrad Harder", team: "Sporting Clube de Portugal", subset: "World Top Clubs", type: "Dominator", persons: ["Conrad Harder"] },

  // Al-Nassr FC (18 cards)
  { number: "NAS1", name: "Club Badge", team: "Al-Nassr FC", subset: "World Top Clubs", type: "Club Badge" },
  { number: "NAS2", name: "Bento", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Bento"] },
  { number: "NAS3", name: "Nawaf Al-Boushal", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Nawaf Al-Boushal"] },
  { number: "NAS4", name: "Sultan Al-Ghannam", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Sultan Al-Ghannam"] },
  { number: "NAS5", name: "Salem Al-Najdi", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Salem Al-Najdi"] },
  { number: "NAS6", name: "Mohamed Simakan", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Mohamed Simakan"] },
  { number: "NAS7", name: "Aymeric Laporte", team: "Al-Nassr FC", subset: "World Top Clubs", type: "Titan", persons: ["Aymeric Laporte"] },
  { number: "NAS8", name: "Mohamed Al-Fatil", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Mohamed Al-Fatil"] },
  { number: "NAS9", name: "Abdullah Al-Khaibari", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Abdullah Al-Khaibari"] },
  { number: "NAS10", name: "Ali Al-Hassan", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Ali Al-Hassan"] },
  { number: "NAS11", name: "Otávio", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Otávio"] },
  { number: "NAS12", name: "Marcelo Brozović", team: "Al-Nassr FC", subset: "World Top Clubs", type: "Magician", persons: ["Marcelo Brozović"] },
  { number: "NAS13", name: "Wesley", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Wesley"] },
  { number: "NAS14", name: "Ayman Yahya", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Ayman Yahya"] },
  { number: "NAS15", name: "Ángelo", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Ángelo"] },
  { number: "NAS16", name: "Sadio Mané", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Sadio Mané"] },
  { number: "NAS17", name: "Abdul Rahman Ghareeb", team: "Al-Nassr FC", subset: "World Top Clubs", persons: ["Abdul Rahman Ghareeb"] },
  { number: "NAS18", name: "Cristiano Ronaldo", team: "Al-Nassr FC", subset: "World Top Clubs", type: "Dominator", persons: ["Cristiano Ronaldo"] },

  // Atlético de Madrid (18 cards)
  { number: "ATM1", name: "Club Badge", team: "Atlético de Madrid", subset: "World Top Clubs", type: "Club Badge" },
  { number: "ATM2", name: "Jan Oblak", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Jan Oblak"] },
  { number: "ATM3", name: "Nahuel Molina", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Nahuel Molina"] },
  { number: "ATM4", name: "Javi Galán", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Javi Galán"] },
  { number: "ATM5", name: "José María Giménez", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["José María Giménez"] },
  { number: "ATM6", name: "Clement Lenglet", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Clement Lenglet"] },
  { number: "ATM7", name: "Robin Le Normand", team: "Atlético de Madrid", subset: "World Top Clubs", type: "Titan", persons: ["Robin Le Normand"] },
  { number: "ATM8", name: "Conor Gallagher", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Conor Gallagher"] },
  { number: "ATM9", name: "Rodrigo De Paul", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Rodrigo De Paul"] },
  { number: "ATM10", name: "Pablo Barrios", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Pablo Barrios"] },
  { number: "ATM11", name: "Koke", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Koke"] },
  { number: "ATM12", name: "Marcos Llorente", team: "Atlético de Madrid", subset: "World Top Clubs", type: "Magician", persons: ["Marcos Llorente"] },
  { number: "ATM13", name: "Samuel Lino", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Samuel Lino"] },
  { number: "ATM14", name: "Giuliano Simeone", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Giuliano Simeone"] },
  { number: "ATM15", name: "Álex Baena", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Álex Baena"] },
  { number: "ATM16", name: "Antoine Griezmann", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Antoine Griezmann"] },
  { number: "ATM17", name: "Alexander Sørloth", team: "Atlético de Madrid", subset: "World Top Clubs", persons: ["Alexander Sørloth"] },
  { number: "ATM18", name: "Julián Álvarez", team: "Atlético de Madrid", subset: "World Top Clubs", type: "Dominator", persons: ["Julián Álvarez"] },

  // FC Barcelona (18 cards)
  { number: "BAR1", name: "Club Badge", team: "FC Barcelona", subset: "World Top Clubs", type: "Club Badge" },
  { number: "BAR2", name: "Wojciech Szczesny", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Wojciech Szczesny"] },
  { number: "BAR3", name: "Joan García", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Joan García"] },
  { number: "BAR4", name: "Jules Koundé", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Jules Koundé"] },
  { number: "BAR5", name: "Alejandro Balde", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Alejandro Balde"] },
  { number: "BAR6", name: "Íñigo Martínez", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Íñigo Martínez"] },
  { number: "BAR7", name: "Ronald Araújo", team: "FC Barcelona", subset: "World Top Clubs", type: "Titan", persons: ["Ronald Araújo"] },
  { number: "BAR8", name: "Pau Cubarsí", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Pau Cubarsí"] },
  { number: "BAR9", name: "Eric García", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Eric García"] },
  { number: "BAR10", name: "Frenkie de Jong", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Frenkie de Jong"] },
  { number: "BAR11", name: "Fermín", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Fermín"] },
  { number: "BAR12", name: "Dani Olmo", team: "FC Barcelona", subset: "World Top Clubs", type: "Magician", persons: ["Dani Olmo"] },
  { number: "BAR13", name: "Gavi", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Gavi"] },
  { number: "BAR14", name: "Pedri", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Pedri"] },
  { number: "BAR15", name: "Ferran Torres", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Ferran Torres"] },
  { number: "BAR16", name: "Lamine Yamal", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Lamine Yamal"] },
  { number: "BAR17", name: "Raphinha", team: "FC Barcelona", subset: "World Top Clubs", persons: ["Raphinha"] },
  { number: "BAR18", name: "Robert Lewandowski", team: "FC Barcelona", subset: "World Top Clubs", type: "Dominator", persons: ["Robert Lewandowski"] },

  // Real Madrid CF (18 cards)
  { number: "RMA1", name: "Club Badge", team: "Real Madrid CF", subset: "World Top Clubs", type: "Club Badge" },
  { number: "RMA2", name: "Thibaut Courtois", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Thibaut Courtois"] },
  { number: "RMA3", name: "Trent Alexander-Arnold", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Trent Alexander-Arnold"] },
  { number: "RMA4", name: "Fran García", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Fran García"] },
  { number: "RMA5", name: "Raul Asencio", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Raul Asencio"] },
  { number: "RMA6", name: "Éder Militão", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Éder Militão"] },
  { number: "RMA7", name: "Antonio Rüdiger", team: "Real Madrid CF", subset: "World Top Clubs", type: "Titan", persons: ["Antonio Rüdiger"] },
  { number: "RMA8", name: "Dean Huijsen", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Dean Huijsen"] },
  { number: "RMA9", name: "Eduardo Camavinga", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Eduardo Camavinga"] },
  { number: "RMA10", name: "Federico Valverde", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Federico Valverde"] },
  { number: "RMA11", name: "Aurélien Tchouaméni", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Aurélien Tchouaméni"] },
  { number: "RMA12", name: "Jude Bellingham", team: "Real Madrid CF", subset: "World Top Clubs", type: "Magician", persons: ["Jude Bellingham"] },
  { number: "RMA13", name: "Franco Mastantuono", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Franco Mastantuono"] },
  { number: "RMA14", name: "Brahim Díaz", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Brahim Díaz"] },
  { number: "RMA15", name: "Vinicius Jr", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Vinicius Jr"] },
  { number: "RMA16", name: "Rodrygo", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Rodrygo"] },
  { number: "RMA17", name: "Endrick", team: "Real Madrid CF", subset: "World Top Clubs", persons: ["Endrick"] },
  { number: "RMA18", name: "Kylian Mbappé", team: "Real Madrid CF", subset: "World Top Clubs", type: "Dominator", persons: ["Kylian Mbappé"] },

  // Road to FIFA World Cup 26 (36 cards)
  { number: "FWC1", name: "Emiliano Martínez", team: "Argentina", subset: "Road to World Cup 26", persons: ["Emiliano Martínez"] },
  { number: "FWC2", name: "Cristian Romero", team: "Argentina", subset: "Road to World Cup 26", persons: ["Cristian Romero"] },
  { number: "FWC3", name: "Nicolás Otamendi", team: "Argentina", subset: "Road to World Cup 26", persons: ["Nicolás Otamendi"] },
  { number: "FWC4", name: "Enzo Fernández", team: "Argentina", subset: "Road to World Cup 26", persons: ["Enzo Fernández"] },
  { number: "FWC5", name: "Rodrigo De Paul", team: "Argentina", subset: "Road to World Cup 26", persons: ["Rodrigo De Paul"] },
  { number: "FWC6", name: "Thiago Almada", team: "Argentina", subset: "Road to World Cup 26", persons: ["Thiago Almada"] },
  { number: "FWC7", name: "Julián Álvarez", team: "Argentina", subset: "Road to World Cup 26", persons: ["Julián Álvarez"] },
  { number: "FWC8", name: "Lionel Messi", team: "Argentina", subset: "Road to World Cup 26", persons: ["Lionel Messi"] },
  { number: "FWC9", name: "Lautaro Martínez", team: "Argentina", subset: "Road to World Cup 26", persons: ["Lautaro Martínez"] },

  { number: "FWC10", name: "Jordan Pickford", team: "England", subset: "Road to World Cup 26", persons: ["Jordan Pickford"] },
  { number: "FWC11", name: "Trent Alexander-Arnold", team: "England", subset: "Road to World Cup 26", persons: ["Trent Alexander-Arnold"] },
  { number: "FWC12", name: "Myles Lewis Skelly", team: "England", subset: "Road to World Cup 26", persons: ["Myles Lewis Skelly"] },
  { number: "FWC13", name: "Declan Rice", team: "England", subset: "Road to World Cup 26", persons: ["Declan Rice"] },
  { number: "FWC14", name: "Jude Bellingham", team: "England", subset: "Road to World Cup 26", persons: ["Jude Bellingham"] },
  { number: "FWC15", name: "Cole Palmer", team: "England", subset: "Road to World Cup 26", persons: ["Cole Palmer"] },
  { number: "FWC16", name: "Phil Foden", team: "England", subset: "Road to World Cup 26", persons: ["Phil Foden"] },
  { number: "FWC17", name: "Bukayo Saka", team: "England", subset: "Road to World Cup 26", persons: ["Bukayo Saka"] },
  { number: "FWC18", name: "Harry Kane", team: "England", subset: "Road to World Cup 26", persons: ["Harry Kane"] },

  { number: "FWC19", name: "Mike Maignan", team: "France", subset: "Road to World Cup 26", persons: ["Mike Maignan"] },
  { number: "FWC20", name: "William Saliba", team: "France", subset: "Road to World Cup 26", persons: ["William Saliba"] },
  { number: "FWC21", name: "Jules Koundé", team: "France", subset: "Road to World Cup 26", persons: ["Jules Koundé"] },
  { number: "FWC22", name: "Manu Koné", team: "France", subset: "Road to World Cup 26", persons: ["Manu Koné"] },
  { number: "FWC23", name: "Aurélien Tchouaméni", team: "France", subset: "Road to World Cup 26", persons: ["Aurélien Tchouaméni"] },
  { number: "FWC24", name: "Michael Olise", team: "France", subset: "Road to World Cup 26", persons: ["Michael Olise"] },
  { number: "FWC25", name: "Désiré Doué", team: "France", subset: "Road to World Cup 26", persons: ["Désiré Doué"] },
  { number: "FWC26", name: "Rayan Cherki", team: "France", subset: "Road to World Cup 26", persons: ["Rayan Cherki"] },
  { number: "FWC27", name: "Kylian Mbappé", team: "France", subset: "Road to World Cup 26", persons: ["Kylian Mbappé"] },

  { number: "FWC28", name: "Unai Simón", team: "Spain", subset: "Road to World Cup 26", persons: ["Unai Simón"] },
  { number: "FWC29", name: "Marc Cucurella", team: "Spain", subset: "Road to World Cup 26", persons: ["Marc Cucurella"] },
  { number: "FWC30", name: "Robin Le Normand", team: "Spain", subset: "Road to World Cup 26", persons: ["Robin Le Normand"] },
  { number: "FWC31", name: "Martin Zubimendi", team: "Spain", subset: "Road to World Cup 26", persons: ["Martin Zubimendi"] },
  { number: "FWC32", name: "Rodri", team: "Spain", subset: "Road to World Cup 26", persons: ["Rodri"] },
  { number: "FWC33", name: "Pedri", team: "Spain", subset: "Road to World Cup 26", persons: ["Pedri"] },
  { number: "FWC34", name: "Mikel Merino", team: "Spain", subset: "Road to World Cup 26", persons: ["Mikel Merino"] },
  { number: "FWC35", name: "Nico Williams", team: "Spain", subset: "Road to World Cup 26", persons: ["Nico Williams"] },
  { number: "FWC36", name: "Lamine Yamal", team: "Spain", subset: "Road to World Cup 26", persons: ["Lamine Yamal"] },

  // Elite Cut (Die-Cut) (18 cards)
  { number: "JWL1", name: "Alisson", team: "Liverpool", subset: "Elite Cut", persons: ["Alisson"] },
  { number: "JWL2", name: "Adrien Rabiot", team: "Olympique de Marseille", subset: "Elite Cut", persons: ["Adrien Rabiot"] },
  { number: "JWL3", name: "Khvicha Kvaratskhelia", team: "Paris Saint-Germain", subset: "Elite Cut", persons: ["Khvicha Kvaratskhelia"] },
  { number: "JWL4", name: "Francesco Acerbi", team: "FC Internazionale Milano", subset: "Elite Cut", persons: ["Francesco Acerbi"] },
  { number: "JWL5", name: "Julián Álvarez", team: "Atlético de Madrid", subset: "Elite Cut", persons: ["Julián Álvarez"] },
  { number: "JWL6", name: "Pedri", team: "FC Barcelona", subset: "Elite Cut", persons: ["Pedri"] },
  { number: "JWL7", name: "Raphinha", team: "FC Barcelona", subset: "Elite Cut", persons: ["Raphinha"] },
  { number: "JWL8", name: "Rodrygo", team: "Real Madrid CF", subset: "Elite Cut", persons: ["Rodrygo"] },
  { number: "JWL9", name: "Vinicius Jr.", team: "Real Madrid CF", subset: "Elite Cut", persons: ["Vinicius Jr"] },
  { number: "JWL10", name: "Kylian Mbappé", team: "Real Madrid CF", subset: "Elite Cut", persons: ["Kylian Mbappé"] },
  { number: "JWL11", name: "Enzo Fernández", team: "Argentina", subset: "Elite Cut", persons: ["Enzo Fernández"] },
  { number: "JWL12", name: "Jude Bellingham", team: "England", subset: "Elite Cut", persons: ["Jude Bellingham"] },
  { number: "JWL13", name: "Declan Rice", team: "England", subset: "Elite Cut", persons: ["Declan Rice"] },
  { number: "JWL14", name: "Désiré Doué", team: "France", subset: "Elite Cut", persons: ["Désiré Doué"] },
  { number: "JWL15", name: "Antonio Rüdiger", team: "Germany", subset: "Elite Cut", persons: ["Antonio Rüdiger"] },
  { number: "JWL16", name: "Martin Ødegaard", team: "Norway", subset: "Elite Cut", persons: ["Martin Ødegaard"] },
  { number: "JWL17", name: "Erling Haaland", team: "Norway", subset: "Elite Cut", persons: ["Erling Haaland"] },
  { number: "JWL18", name: "Lamine Yamal", team: "Spain", subset: "Elite Cut", persons: ["Lamine Yamal"] },

  // Fans' Favourite (100 cards)
  { number: "FAN1", name: "Alisson", team: "Liverpool", subset: "Fans' Favourite", persons: ["Alisson"] },
  { number: "FAN2", name: "Jerzy Dudek", team: "Liverpool", subset: "Fans' Favourite", type: "Legend", persons: ["Jerzy Dudek"] },
  { number: "FAN3", name: "Gianluigi Donnarumma", team: "Paris Saint-Germain", subset: "Fans' Favourite", persons: ["Gianluigi Donnarumma"] },
  { number: "FAN4", name: "Mike Maignan", team: "AC Milan", subset: "Fans' Favourite", persons: ["Mike Maignan"] },
  { number: "FAN5", name: "Jan Oblak", team: "Atlético de Madrid", subset: "Fans' Favourite", persons: ["Jan Oblak"] },
  { number: "FAN6", name: "Thibaut Courtois", team: "Real Madrid CF", subset: "Fans' Favourite", persons: ["Thibaut Courtois"] },
  { number: "FAN7", name: "Emiliano Martínez", team: "Argentina", subset: "Fans' Favourite", persons: ["Emiliano Martínez"] },
  { number: "FAN8", name: "Jair Cunha", team: "Botafogo", subset: "Fans' Favourite", persons: ["Jair Cunha"] },
  { number: "FAN9", name: "Virgil van Dijk", team: "Liverpool", subset: "Fans' Favourite", persons: ["Virgil van Dijk"] },
  { number: "FAN10", name: "Achraf Hakimi", team: "Paris Saint-Germain", subset: "Fans' Favourite", persons: ["Achraf Hakimi"] },
  { number: "FAN11", name: "Piero Hincapié", team: "Bayer 04 Leverkusen", subset: "Fans' Favourite", persons: ["Piero Hincapié"] },
  { number: "FAN12", name: "Lucio", team: "Bayer 04 Leverkusen", subset: "Fans' Favourite", type: "Legend", persons: ["Lucio"] },
  { number: "FAN13", name: "Alessandro Bastoni", team: "FC Internazionale Milano", subset: "Fans' Favourite", persons: ["Alessandro Bastoni"] },
  { number: "FAN14", name: "Federico Dimarco", team: "FC Internazionale Milano", subset: "Fans' Favourite", persons: ["Federico Dimarco"] },
  { number: "FAN15", name: "Matteo Gabbia", team: "AC Milan", subset: "Fans' Favourite", persons: ["Matteo Gabbia"] },
  { number: "FAN16", name: "Paolo Maldini", team: "AC Milan", subset: "Fans' Favourite", type: "Legend", persons: ["Paolo Maldini"] },
  { number: "FAN17", name: "Jorrel Hato", team: "AFC Ajax", subset: "Fans' Favourite", persons: ["Jorrel Hato"] },
  { number: "FAN18", name: "Morten Hjulmand", team: "Sporting Clube de Portugal", subset: "Fans' Favourite", persons: ["Morten Hjulmand"] },
  { number: "FAN19", name: "Ronald Araújo", team: "FC Barcelona", subset: "Fans' Favourite", persons: ["Ronald Araújo"] },
  { number: "FAN20", name: "Jules Koundé", team: "FC Barcelona", subset: "Fans' Favourite", persons: ["Jules Koundé"] },
  { number: "FAN21", name: "William Saliba", team: "France", subset: "Fans' Favourite", persons: ["William Saliba"] },
  { number: "FAN22", name: "Daniel Carvajal", team: "Spain", subset: "Fans' Favourite", persons: ["Daniel Carvajal"] },
  { number: "FAN23", name: "Gerard Piqué", team: "Spain", subset: "Fans' Favourite", type: "Legend", persons: ["Gerard Piqué"] },
  { number: "FAN24", name: "Dominik Szoboszlai", team: "Liverpool", subset: "Fans' Favourite", persons: ["Dominik Szoboszlai"] },
  { number: "FAN25", name: "Florian Wirtz", team: "Liverpool", subset: "Fans' Favourite", persons: ["Florian Wirtz"] },
  { number: "FAN26", name: "Adrien Rabiot", team: "Olympique de Marseille", subset: "Fans' Favourite", persons: ["Adrien Rabiot"] },
  { number: "FAN27", name: "Geoffrey Kondogbia", team: "Olympique de Marseille", subset: "Fans' Favourite", persons: ["Geoffrey Kondogbia"] },
  { number: "FAN28", name: "Vitinha", team: "Paris Saint-Germain", subset: "Fans' Favourite", persons: ["Vitinha"] },
  { number: "FAN29", name: "Alejandro Grimaldo", team: "Bayer 04 Leverkusen", subset: "Fans' Favourite", persons: ["Alejandro Grimaldo"] },
  { number: "FAN30", name: "Bernd Schneider", team: "Bayer 04 Leverkusen", subset: "Fans' Favourite", type: "Legend", persons: ["Bernd Schneider"] },
  { number: "FAN31", name: "Nicolò Barella", team: "FC Internazionale Milano", subset: "Fans' Favourite", persons: ["Nicolò Barella"] },
  { number: "FAN32", name: "Hakan Çalhanoğlu", team: "FC Internazionale Milano", subset: "Fans' Favourite", persons: ["Hakan Çalhanoğlu"] },
  { number: "FAN33", name: "Andrea Pirlo", team: "AC Milan", subset: "Fans' Favourite", type: "Legend", persons: ["Andrea Pirlo"] },
  { number: "FAN34", name: "Christian Pulisic", team: "AC Milan", subset: "Fans' Favourite", persons: ["Christian Pulisic"] },
  { number: "FAN35", name: "Wesley Sneijder", team: "AFC Ajax", subset: "Fans' Favourite", type: "Legend", persons: ["Wesley Sneijder"] },
  { number: "FAN36", name: "Kenneth Taylor", team: "AFC Ajax", subset: "Fans' Favourite", persons: ["Kenneth Taylor"] },
  { number: "FAN37", name: "Luís Figo", team: "Sporting Clube de Portugal", subset: "Fans' Favourite", type: "Legend", persons: ["Luís Figo"] },
  { number: "FAN38", name: "Pablo Barrios", team: "Atlético de Madrid", subset: "Fans' Favourite", persons: ["Pablo Barrios"] },
  { number: "FAN39", name: "Rodrigo De Paul", team: "Atlético de Madrid", subset: "Fans' Favourite", persons: ["Rodrigo De Paul"] },
  { number: "FAN40", name: "Andrés Iniesta", team: "FC Barcelona", subset: "Fans' Favourite", type: "Legend", persons: ["Andrés Iniesta"] },
  { number: "FAN41", name: "Pedri", team: "FC Barcelona", subset: "Fans' Favourite", persons: ["Pedri"] },
  { number: "FAN42", name: "Jude Bellingham", team: "Real Madrid CF", subset: "Fans' Favourite", persons: ["Jude Bellingham"] },
  { number: "FAN43", name: "Eduardo Camavinga", team: "Real Madrid CF", subset: "Fans' Favourite", persons: ["Eduardo Camavinga"] },
  { number: "FAN44", name: "Aurélien Tchouaméni", team: "Real Madrid CF", subset: "Fans' Favourite", persons: ["Aurélien Tchouaméni"] },
  { number: "FAN45", name: "Federico Valverde", team: "Real Madrid CF", subset: "Fans' Favourite", persons: ["Federico Valverde"] },
  { number: "FAN46", name: "Enzo Fernández", team: "Argentina", subset: "Fans' Favourite", persons: ["Enzo Fernández"] },
  { number: "FAN47", name: "Alexis Mac Allister", team: "Argentina", subset: "Fans' Favourite", persons: ["Alexis Mac Allister"] },
  { number: "FAN48", name: "Declan Rice", team: "England", subset: "Fans' Favourite", persons: ["Declan Rice"] },
  { number: "FAN49", name: "Morgan Rogers", team: "England", subset: "Fans' Favourite", persons: ["Morgan Rogers"] },
  { number: "FAN50", name: "Warren Zaïre-Emery", team: "France", subset: "Fans' Favourite", persons: ["Warren Zaïre-Emery"] },
  { number: "FAN51", name: "Zinedine Zidane", team: "France", subset: "Fans' Favourite", type: "Legend", persons: ["Zinedine Zidane"] },
  { number: "FAN52", name: "Pascal Groß", team: "Germany", subset: "Fans' Favourite", persons: ["Pascal Groß"] },
  { number: "FAN53", name: "Joshua Kimmich", team: "Germany", subset: "Fans' Favourite", persons: ["Joshua Kimmich"] },
  { number: "FAN54", name: "Jamal Musiala", team: "Germany", subset: "Fans' Favourite", persons: ["Jamal Musiala"] },
  { number: "FAN55", name: "Martin Ødegaard", team: "Norway", subset: "Fans' Favourite", persons: ["Martin Ødegaard"] },
  { number: "FAN56", name: "Rodri", team: "Spain", subset: "Fans' Favourite", persons: ["Rodri"] },
  { number: "FAN57", name: "Igor Jesus", team: "Botafogo", subset: "Fans' Favourite", persons: ["Igor Jesus"] },
  { number: "FAN58", name: "Michael Owen", team: "Liverpool", subset: "Fans' Favourite", type: "Legend", persons: ["Michael Owen"] },
  { number: "FAN59", name: "Mohamed Salah", team: "Liverpool", subset: "Fans' Favourite", persons: ["Mohamed Salah"] },
  { number: "FAN60", name: "Neal Maupay", team: "Olympique de Marseille", subset: "Fans' Favourite", persons: ["Neal Maupay"] },
  { number: "FAN61", name: "Désiré Doué", team: "Paris Saint-Germain", subset: "Fans' Favourite", persons: ["Désiré Doué"] },
  { number: "FAN62", name: "Jonathan Burkardt", team: "Eintracht Frankfurt", subset: "Fans' Favourite", persons: ["Jonathan Burkardt"] },
  { number: "FAN63", name: "Lautaro Martínez", team: "FC Internazionale Milano", subset: "Fans' Favourite", persons: ["Lautaro Martínez"] },
  { number: "FAN64", name: "Iván Zamorano", team: "FC Internazionale Milano", subset: "Fans' Favourite", type: "Legend", persons: ["Iván Zamorano"] },
  { number: "FAN65", name: "Marcus Thuram", team: "FC Internazionale Milano", subset: "Fans' Favourite", persons: ["Marcus Thuram"] },
  { number: "FAN66", name: "Cristiano Ronaldo", team: "Al-Nassr FC", subset: "Fans' Favourite", persons: ["Cristiano Ronaldo"] },
  { number: "FAN67", name: "Rafael Leão", team: "AC Milan", subset: "Fans' Favourite", persons: ["Rafael Leão"] },
  { number: "FAN68", name: "Sadio Mané", team: "Al-Nassr FC", subset: "Fans' Favourite", persons: ["Sadio Mané"] },
  { number: "FAN69", name: "Geovany Quenda", team: "Sporting Clube de Portugal", subset: "Fans' Favourite", persons: ["Geovany Quenda"] },
  { number: "FAN70", name: "Sergio Agüero", team: "Atlético de Madrid", subset: "Fans' Favourite", type: "Legend", persons: ["Sergio Agüero"] },
  { number: "FAN71", name: "Antoine Griezmann", team: "Atlético de Madrid", subset: "Fans' Favourite", persons: ["Antoine Griezmann"] },
  { number: "FAN72", name: "Henrik Larsson", team: "FC Barcelona", subset: "Fans' Favourite", type: "Legend", persons: ["Henrik Larsson"] },
  { number: "FAN73", name: "Robert Lewandowski", team: "FC Barcelona", subset: "Fans' Favourite", persons: ["Robert Lewandowski"] },
  { number: "FAN74", name: "Raphinha", team: "FC Barcelona", subset: "Fans' Favourite", persons: ["Raphinha"] },
  { number: "FAN75", name: "Lamine Yamal", team: "FC Barcelona", subset: "Fans' Favourite", persons: ["Lamine Yamal"] },
  { number: "FAN76", name: "Michael Laudrup", team: "Real Madrid CF", subset: "Fans' Favourite", type: "Legend", persons: ["Michael Laudrup"] },
  { number: "FAN77", name: "Rodrygo", team: "Real Madrid CF", subset: "Fans' Favourite", persons: ["Rodrygo"] },
  { number: "FAN78", name: "Ruud van Nistelrooy", team: "Real Madrid CF", subset: "Fans' Favourite", type: "Legend", persons: ["Ruud van Nistelrooy"] },
  { number: "FAN79", name: "Vinicius Jr.", team: "Real Madrid CF", subset: "Fans' Favourite", persons: ["Vinicius Jr"] },
  { number: "FAN80", name: "Tim Kleindienst", team: "Germany", subset: "Fans' Favourite", persons: ["Tim Kleindienst"] },
  { number: "FAN81", name: "Leroy Sané", team: "Germany", subset: "Fans' Favourite", persons: ["Leroy Sané"] },
  { number: "FAN82", name: "Deniz Undav", team: "Germany", subset: "Fans' Favourite", persons: ["Deniz Undav"] },
  { number: "FAN83", name: "Julián Álvarez", team: "Argentina", subset: "Fans' Favourite", persons: ["Julián Álvarez"] },
  { number: "FAN84", name: "Lionel Messi", team: "Argentina", subset: "Fans' Favourite", persons: ["Lionel Messi"] },
  { number: "FAN85", name: "Phil Foden", team: "England", subset: "Fans' Favourite", persons: ["Phil Foden"] },
  { number: "FAN86", name: "Harry Kane", team: "England", subset: "Fans' Favourite", persons: ["Harry Kane"] },
  { number: "FAN87", name: "Cole Palmer", team: "England", subset: "Fans' Favourite", persons: ["Cole Palmer"] },
  { number: "FAN88", name: "Bukayo Saka", team: "England", subset: "Fans' Favourite", persons: ["Bukayo Saka"] },
  { number: "FAN89", name: "Alan Shearer", team: "England", subset: "Fans' Favourite", type: "Legend", persons: ["Alan Shearer"] },
  { number: "FAN90", name: "Bradley Barcola", team: "France", subset: "Fans' Favourite", persons: ["Bradley Barcola"] },
  { number: "FAN91", name: "Ousmane Dembélé", team: "France", subset: "Fans' Favourite", persons: ["Ousmane Dembélé"] },
  { number: "FAN92", name: "Kylian Mbappé", team: "France", subset: "Fans' Favourite", persons: ["Kylian Mbappé"] },
  { number: "FAN93", name: "Randal Kolo Muani", team: "France", subset: "Fans' Favourite", persons: ["Randal Kolo Muani"] },
  { number: "FAN94", name: "David Trezeguet", team: "France", subset: "Fans' Favourite", type: "Legend", persons: ["David Trezeguet"] },
  { number: "FAN95", name: "Rasmus Højlund", team: "Denmark", subset: "Fans' Favourite", persons: ["Rasmus Højlund"] },
  { number: "FAN96", name: "Erling Haaland", team: "Norway", subset: "Fans' Favourite", persons: ["Erling Haaland"] },
  { number: "FAN97", name: "Mikel Oyarzabal", team: "Spain", subset: "Fans' Favourite", persons: ["Mikel Oyarzabal"] },
  { number: "FAN98", name: "Nico Williams", team: "Spain", subset: "Fans' Favourite", persons: ["Nico Williams"] },
  { number: "FAN99", name: "Aleksander Isak", team: "Sweden", subset: "Fans' Favourite", persons: ["Aleksander Isak"] },
  { number: "FAN100", name: "Dejan Kulusevski", team: "Sweden", subset: "Fans' Favourite", persons: ["Dejan Kulusevski"] },

  // Momentum (8 cards)
  { number: "MOM1", name: "Alexander Isak", team: "Liverpool", subset: "Momentum", type: "Star Signings Upgrade Box", persons: ["Alexander Isak"] },
  { number: "MOM2", name: "Mohamed Salah", team: "Liverpool", subset: "Momentum", persons: ["Mohamed Salah"] },
  { number: "MOM3", name: "Désiré Doué", team: "Paris Saint-Germain", subset: "Momentum", type: "Pencil Tin (Hungary)", persons: ["Désiré Doué"] },
  { number: "MOM4", name: "Lautaro Martínez", team: "FC Internazionale Milano", subset: "Momentum", persons: ["Lautaro Martínez"] },
  { number: "MOM5", name: "Luka Modrić", team: "AC Milan", subset: "Momentum", persons: ["Luka Modrić"] },
  { number: "MOM6", name: "Lamine Yamal", team: "FC Barcelona", subset: "Momentum", type: "Pencil Tin (Hungary)", persons: ["Lamine Yamal"] },
  { number: "MOM7", name: "Declan Rice", team: "England", subset: "Momentum", persons: ["Declan Rice"] },
  { number: "MOM8", name: "Kylian Mbappé", team: "France", subset: "Momentum", type: "Excellence", persons: ["Kylian Mbappé"] },

  // Invincible Momentum (1 card)
  { number: "IM1", name: "Kylian Mbappé", team: "Real Madrid CF", subset: "Invincible Momentum", type: "Pencil Tin (Hungary)", persons: ["Kylian Mbappé"] },
  { number: "IM2", name: "Gianluigi Donnarumma", team: "Paris Saint-Germain", subset: "Invincible Momentum", persons: ["Gianluigi Donnarumma"] },
  { number: "IM3", name: "Raphinha", team: "FC Barcelona", subset: "Invincible Momentum", persons: ["Raphinha"] },
  { number: "IM4", name: "Virgil van Dijk", team: "Liverpool", subset: "Invincible Momentum", persons: ["Virgil van Dijk"] },

  // Rising Star (6 cards)
  { number: "RS1", name: "Nico Paz", team: "Argentina", subset: "Rising Star", persons: ["Nico Paz"] },
  { number: "RS2", name: "Senny Mayulu", team: "Paris Saint-Germain", subset: "Rising Star", persons: ["Senny Mayulu"] },
  { number: "RS3", name: "Alex Jiménez", team: "AC Milan", subset: "Rising Star", persons: ["Alex Jiménez"] },
  { number: "RS4", name: "Jorrel Hato", team: "AFC Ajax", subset: "Rising Star", persons: ["Jorrel Hato"] },
  { number: "RS5", name: "Geovany Quenda", team: "Sporting Clube de Portugal", subset: "Rising Star", persons: ["Geovany Quenda"] },
  { number: "RS6", name: "Marc Bernal", team: "FC Barcelona", subset: "Rising Star", persons: ["Marc Bernal"] },

  // Club 99 (24 cards)
  { number: "CLB1", name: "Alexis Mac Allister", team: "Liverpool", subset: "Club 99", persons: ["Alexis Mac Allister"] },
  { number: "CLB2", name: "Cody Gakpo", team: "Liverpool", subset: "Club 99", persons: ["Cody Gakpo"] },
  { number: "CLB3", name: "Fabián Ruiz", team: "Paris Saint-Germain", subset: "Club 99", persons: ["Fabián Ruiz"] },
  { number: "CLB4", name: "Bradley Barcola", team: "Paris Saint-Germain", subset: "Club 99", persons: ["Bradley Barcola"] },
  { number: "CLB5", name: "Granit Xhaka", team: "Bayer 04 Leverkusen", subset: "Club 99", persons: ["Granit Xhaka"] },
  { number: "CLB6", name: "Denzel Dumfries", team: "FC Internazionale Milano", subset: "Club 99", persons: ["Denzel Dumfries"] },
  { number: "CLB7", name: "Lautaro Martínez", team: "FC Internazionale Milano", subset: "Club 99", persons: ["Lautaro Martínez"] },
  { number: "CLB8", name: "Santiago Giménez", team: "AC Milan", subset: "Club 99", persons: ["Santiago Giménez"] },
  { number: "CLB9", name: "Trincão", team: "Sporting Clube de Portugal", subset: "Club 99", persons: ["Trincão"] },
  { number: "CLB10", name: "Cristiano Ronaldo", team: "Al-Nassr FC", subset: "Club 99", persons: ["Cristiano Ronaldo"] },
  { number: "CLB11", name: "Giuliano Simeone", team: "Atlético de Madrid", subset: "Club 99", persons: ["Giuliano Simeone"] },
  { number: "CLB12", name: "Wojciech Szczęsny", team: "FC Barcelona", subset: "Club 99", persons: ["Wojciech Szczęsny"] },
  { number: "CLB13", name: "Lamine Yamal", team: "FC Barcelona", subset: "Club 99", persons: ["Lamine Yamal"] },
  { number: "CLB14", name: "Jude Bellingham", team: "Real Madrid CF", subset: "Club 99", persons: ["Jude Bellingham"] },
  { number: "CLB15", name: "Kylian Mbappé", team: "Real Madrid CF", subset: "Club 99", persons: ["Kylian Mbappé"] },
  { number: "CLB16", name: "Lautaro Martínez", team: "Argentina", subset: "Club 99", persons: ["Lautaro Martínez"] },
  { number: "CLB17", name: "Phil Foden", team: "England", subset: "Club 99", persons: ["Phil Foden"] },
  { number: "CLB18", name: "Harry Kane", team: "England", subset: "Club 99", persons: ["Harry Kane"] },
  { number: "CLB19", name: "Marcus Rashford", team: "England", subset: "Club 99", persons: ["Marcus Rashford"] },
  { number: "CLB20", name: "Dayot Upamecano", team: "France", subset: "Club 99", persons: ["Dayot Upamecano"] },
  { number: "CLB21", name: "Marc-André ter Stegen", team: "Germany", subset: "Club 99", persons: ["Marc-André ter Stegen"] },
  { number: "CLB22", name: "Florian Wirtz", team: "Germany", subset: "Club 99", persons: ["Florian Wirtz"] },
  { number: "CLB23", name: "Erling Haaland", team: "Norway", subset: "Club 99", persons: ["Erling Haaland"] },
  { number: "CLB24", name: "Viktor Gyökeres", team: "Sweden", subset: "Club 99", persons: ["Viktor Gyökeres"] },

  // Star Signings (48 cards)
  { number: "STS01", name: "Danilo", team: "Botafogo", subset: "Star Signings", persons: ["Danilo"] },
  { number: "STS02", name: "Álvaro Montoro", team: "Botafogo", subset: "Star Signings", persons: ["Álvaro Montoro"] },
  { number: "STS03", name: "Giovanni Leoni", team: "Liverpool", subset: "Star Signings", persons: ["Giovanni Leoni"] },
  { number: "STS04", name: "Milos Kerkez", team: "Liverpool", subset: "Star Signings", persons: ["Milos Kerkez"] },
  { number: "STS05", name: "Jeremie Frimpong", team: "Liverpool", subset: "Star Signings", persons: ["Jeremie Frimpong"] },
  { number: "STS06", name: "Florian Wirtz", team: "Liverpool", subset: "Star Signings", persons: ["Florian Wirtz"] },
  { number: "STS07", name: "Hugo Ekitike", team: "Liverpool", subset: "Star Signings", persons: ["Hugo Ekitike"] },
  { number: "STS08", name: "Igor Paixão", team: "Olympique de Marseille", subset: "Star Signings", persons: ["Igor Paixão"] },
  { number: "STS09", name: "Pierre-Emerick Aubameyang", team: "Olympique de Marseille", subset: "Star Signings", persons: ["Pierre-Emerick Aubameyang"] },
  { number: "STS10", name: "Lucas Chevalier", team: "Paris Saint-Germain", subset: "Star Signings", persons: ["Lucas Chevalier"] },
  { number: "STS11", name: "Ilya Zabarnyi", team: "Paris Saint-Germain", subset: "Star Signings", persons: ["Ilya Zabarnyi"] },
  { number: "STS12", name: "Mark Flekken", team: "Bayer 04 Leverkusen", subset: "Star Signings", persons: ["Mark Flekken"] },
  { number: "STS13", name: "Lucas Vazquez", team: "Bayer 04 Leverkusen", subset: "Star Signings", persons: ["Lucas Vazquez"] },
  { number: "STS14", name: "Claudio Echeverri", team: "Bayer 04 Leverkusen", subset: "Star Signings", persons: ["Claudio Echeverri"] },
  { number: "STS15", name: "Malik Tillman", team: "Bayer 04 Leverkusen", subset: "Star Signings", persons: ["Malik Tillman"] },
  { number: "STS16", name: "Ellesse Ben Seghir", team: "Bayer 04 Leverkusen", subset: "Star Signings", persons: ["Ellesse Ben Seghir"] },
  { number: "STS17", name: "Ritsu Doan", team: "Eintracht Frankfurt", subset: "Star Signings", persons: ["Ritsu Doan"] },
  { number: "STS18", name: "Jonathan Burkardt", team: "Eintracht Frankfurt", subset: "Star Signings", persons: ["Jonathan Burkardt"] },
  { number: "STS19", name: "Gabriel Strefezza", team: "Olympiacos FC", subset: "Star Signings", persons: ["Gabriel Strefezza"] },
  { number: "STS20", name: "Mehdi Taremi", team: "Olympiacos FC", subset: "Star Signings", persons: ["Mehdi Taremi"] },
  { number: "STS21", name: "Manuel Akanji", team: "FC Internazionale Milano", subset: "Star Signings", persons: ["Manuel Akanji"] },
  { number: "STS22", name: "Petar Sučić", team: "FC Internazionale Milano", subset: "Star Signings", persons: ["Petar Sučić"] },
  { number: "STS23", name: "Ange-Yoan Bonny", team: "FC Internazionale Milano", subset: "Star Signings", persons: ["Ange-Yoan Bonny"] },
  { number: "STS24", name: "Pio Esposito", team: "FC Internazionale Milano", subset: "Star Signings", persons: ["Pio Esposito"] },
  { number: "STS25", name: "Pervis Estupiñán", team: "AC Milan", subset: "Star Signings", persons: ["Pervis Estupiñán"] },
  { number: "STS26", name: "Ardon Jashari", team: "AC Milan", subset: "Star Signings", persons: ["Ardon Jashari"] },
  { number: "STS27", name: "Luka Modrić", team: "AC Milan", subset: "Star Signings", persons: ["Luka Modrić"] },
  { number: "STS28", name: "Adrien Rabiot", team: "AC Milan", subset: "Star Signings", persons: ["Adrien Rabiot"] },
  { number: "STS29", name: "Christopher Nkunku", team: "AC Milan", subset: "Star Signings", persons: ["Christopher Nkunku"] },
  { number: "STS30", name: "Vítězslav Jaroš", team: "AC Milan", subset: "Star Signings", persons: ["Vítězslav Jaroš"] },
  { number: "STS31", name: "Oscar Gloukh", team: "AFC Ajax", subset: "Star Signings", persons: ["Oscar Gloukh"] },
  { number: "STS32", name: "Raúl Moro", team: "AFC Ajax", subset: "Star Signings", persons: ["Raúl Moro"] },
  { number: "STS33", name: "Kasper Dolberg", team: "AFC Ajax", subset: "Star Signings", persons: ["Kasper Dolberg"] },
  { number: "STS34", name: "Paul Wanner", team: "PSV Eindhoven", subset: "Star Signings", persons: ["Paul Wanner"] },
  { number: "STS35", name: "Ruben van Bommel", team: "PSV Eindhoven", subset: "Star Signings", persons: ["Ruben van Bommel"] },
  { number: "STS36", name: "Dennis Man", team: "PSV Eindhoven", subset: "Star Signings", persons: ["Dennis Man"] },
  { number: "STS37", name: "Fotis Ioannidis", team: "Sporting Clube de Portugal", subset: "Star Signings", persons: ["Fotis Ioannidis"] },
  { number: "STS38", name: "Luis Suárez", team: "Sporting Clube de Portugal", subset: "Star Signings", persons: ["Luis Suárez"] },
  { number: "STS39", name: "Dávid Hancko", team: "Atlético de Madrid", subset: "Star Signings", persons: ["Dávid Hancko"] },
  { number: "STS40", name: "Johnny Cardoso", team: "Atlético de Madrid", subset: "Star Signings", persons: ["Johnny Cardoso"] },
  { number: "STS41", name: "Thiago Almada", team: "Atlético de Madrid", subset: "Star Signings", persons: ["Thiago Almada"] },
  { number: "STS42", name: "Nico Gonzalez", team: "Atlético de Madrid", subset: "Star Signings", persons: ["Nico Gonzalez"] },
  { number: "STS43", name: "Alex Baena", team: "Atlético de Madrid", subset: "Star Signings", persons: ["Alex Baena"] },
  { number: "STS44", name: "Joan García", team: "FC Barcelona", subset: "Star Signings", persons: ["Joan García"] },
  { number: "STS45", name: "Marcus Rashford", team: "FC Barcelona", subset: "Star Signings", persons: ["Marcus Rashford"] },
  { number: "STS46", name: "Dean Huijsen", team: "Real Madrid CF", subset: "Star Signings", persons: ["Dean Huijsen"] },
  { number: "STS47", name: "Trent Alexander Arnold", team: "Real Madrid CF", subset: "Star Signings", persons: ["Trent Alexander Arnold"] },
  { number: "STS48", name: "Álvaro Carreras", team: "Real Madrid CF", subset: "Star Signings", persons: ["Álvaro Carreras"] },

  // Excellence Box - Numb3rs (24 cards)
  { number: "EXC1", name: "Alisson", team: "Liverpool", subset: "Excellence Box", type: "Numb3rs", persons: ["Alisson"] },
  { number: "EXC2", name: "Ashraf Hakimi", team: "Paris Saint-Germain", subset: "Excellence Box", type: "Numb3rs", persons: ["Ashraf Hakimi"] },
  { number: "EXC3", name: "Robin Le Normand", team: "Spain", subset: "Excellence Box", type: "Numb3rs", persons: ["Robin Le Normand"] },
  { number: "EXC4", name: "Declan Rice", team: "England", subset: "Excellence Box", type: "Numb3rs", persons: ["Declan Rice"] },
  { number: "EXC5", name: "Jude Bellingham", team: "England", subset: "Excellence Box", type: "Numb3rs", persons: ["Jude Bellingham"] },
  { number: "EXC6", name: "Milos Kerkez", team: "Liverpool", subset: "Excellence Box", type: "Numb3rs", persons: ["Milos Kerkez"] },
  { number: "EXC7", name: "Rodrigo De Paul", team: "Argentina", subset: "Excellence Box", type: "Numb3rs", persons: ["Rodrigo De Paul"] },
  { number: "EXC8", name: "Aurélien Tchouaméni", team: "France", subset: "Excellence Box", type: "Numb3rs", persons: ["Aurélien Tchouaméni"] },
  { number: "EXC9", name: "Erling Haaland", team: "Norway", subset: "Excellence Box", type: "Numb3rs", persons: ["Erling Haaland"] },
  { number: "EXC10", name: "Lamine Yamal", team: "FC Barcelona", subset: "Excellence Box", type: "Numb3rs", persons: ["Lamine Yamal"] },
  { number: "EXC11", name: "Mohamed Salah", team: "Liverpool", subset: "Excellence Box", type: "Numb3rs", persons: ["Mohamed Salah"] },
  { number: "EXC12", name: "Désiré Doué", team: "France", subset: "Excellence Box", type: "Numb3rs", persons: ["Désiré Doué"] },
  { number: "EXC13", name: "Cristian Romero", team: "Argentina", subset: "Excellence Box", type: "Numb3rs", persons: ["Cristian Romero"] },
  { number: "EXC14", name: "Igor Paixão", team: "Olympique de Marseille", subset: "Excellence Box", type: "Numb3rs", persons: ["Igor Paixão"] },
  { number: "EXC15", name: "Eberechi Eze", team: "England", subset: "Excellence Box", type: "Numb3rs", persons: ["Eberechi Eze"] },
  { number: "EXC16", name: "Mike Maignan", team: "AC Milan", subset: "Excellence Box", type: "Numb3rs", persons: ["Mike Maignan"] },
  { number: "EXC17", name: "Nico Williams", team: "Spain", subset: "Excellence Box", type: "Numb3rs", persons: ["Nico Williams"] },
  { number: "EXC18", name: "Martin Zubimendi", team: "Spain", subset: "Excellence Box", type: "Numb3rs", persons: ["Martin Zubimendi"] },
  { number: "EXC19", name: "Julián Álvarez", team: "Atlético de Madrid", subset: "Excellence Box", type: "Numb3rs", persons: ["Julián Álvarez"] },
  { number: "EXC20", name: "Cole Palmer", team: "England", subset: "Excellence Box", type: "Numb3rs", persons: ["Cole Palmer"] },
  { number: "EXC21", name: "Frenkie de Jong", team: "FC Barcelona", subset: "Excellence Box", type: "Numb3rs", persons: ["Frenkie de Jong"] },
  { number: "EXC22", name: "Hugo Ekitike", team: "Liverpool", subset: "Excellence Box", type: "Numb3rs", persons: ["Hugo Ekitike"] },
  { number: "EXC23", name: "Nicolò Barella", team: "FC Internazionale Milano", subset: "Excellence Box", type: "Numb3rs", persons: ["Nicolò Barella"] },
  { number: "EXC24", name: "Dean Huijsen", team: "Real Madrid CF", subset: "Excellence Box", type: "Numb3rs", persons: ["Dean Huijsen"] },

  // Excellence Box - Aura (24 cards)
  { number: "EXC25", name: "Alexis Mac Allister", team: "Liverpool", subset: "Excellence Box", type: "Aura", persons: ["Alexis Mac Allister"] },
  { number: "EXC26", name: "Dominik Szoboszlai", team: "Liverpool", subset: "Excellence Box", type: "Aura", persons: ["Dominik Szoboszlai"] },
  { number: "EXC27", name: "Benjamin Pavard", team: "Olympique de Marseille", subset: "Excellence Box", type: "Aura", persons: ["Benjamin Pavard"] },
  { number: "EXC28", name: "Pierre-Emerick Aubameyang", team: "Olympique de Marseille", subset: "Excellence Box", type: "Aura", persons: ["Pierre-Emerick Aubameyang"] },
  { number: "EXC29", name: "Vitinha", team: "Paris Saint-Germain", subset: "Excellence Box", type: "Aura", persons: ["Vitinha"] },
  { number: "EXC30", name: "Khvicha Kvaratskhelia", team: "Paris Saint-Germain", subset: "Excellence Box", type: "Aura", persons: ["Khvicha Kvaratskhelia"] },
  { number: "EXC31", name: "Lautaro Martínez", team: "FC Internazionale Milano", subset: "Excellence Box", type: "Aura", persons: ["Lautaro Martínez"] },
  { number: "EXC32", name: "Marcus Thuram", team: "FC Internazionale Milano", subset: "Excellence Box", type: "Aura", persons: ["Marcus Thuram"] },
  { number: "EXC33", name: "Pedri", team: "FC Barcelona", subset: "Excellence Box", type: "Aura", persons: ["Pedri"] },
  { number: "EXC34", name: "Raphinha", team: "FC Barcelona", subset: "Excellence Box", type: "Aura", persons: ["Raphinha"] },
  { number: "EXC35", name: "Kylian Mbappé", team: "Real Madrid CF", subset: "Excellence Box", type: "Aura", persons: ["Kylian Mbappé"] },
  { number: "EXC36", name: "Vini Jr", team: "Real Madrid CF", subset: "Excellence Box", type: "Aura", persons: ["Vini Jr"] },
  { number: "EXC37", name: "Enzo Fernández", team: "Argentina", subset: "Excellence Box", type: "Aura", persons: ["Enzo Fernández"] },
  { number: "EXC38", name: "Phil Foden", team: "England", subset: "Excellence Box", type: "Aura", persons: ["Phil Foden"] },
  { number: "EXC39", name: "Harry Kane", team: "England", subset: "Excellence Box", type: "Aura", persons: ["Harry Kane"] },
  { number: "EXC40", name: "Ousmane Dembélé", team: "France", subset: "Excellence Box", type: "Aura", persons: ["Ousmane Dembélé"] },
  { number: "EXC41", name: "Michael Olise", team: "France", subset: "Excellence Box", type: "Aura", persons: ["Michael Olise"] },
  { number: "EXC42", name: "Mike Maignan", team: "France", subset: "Excellence Box", type: "Aura", persons: ["Mike Maignan"] },
  { number: "EXC43", name: "Jonathan Tah", team: "Germany", subset: "Excellence Box", type: "Aura", persons: ["Jonathan Tah"] },
  { number: "EXC44", name: "Nick Woltemade", team: "Germany", subset: "Excellence Box", type: "Aura", persons: ["Nick Woltemade"] },
  { number: "EXC45", name: "Antonio Nusa", team: "Norway", subset: "Excellence Box", type: "Aura", persons: ["Antonio Nusa"] },
  { number: "EXC46", name: "Erling Haaland", team: "Norway", subset: "Excellence Box", type: "Aura", persons: ["Erling Haaland"] },
  { number: "EXC47", name: "Martin Ødegaard", team: "Norway", subset: "Excellence Box", type: "Aura", persons: ["Martin Ødegaard"] },
  { number: "EXC48", name: "Nico Williams", team: "Spain", subset: "Excellence Box", type: "Aura", persons: ["Nico Williams"] },

  // Limited Edition (189 cards) - Key players
  { number: "LE1", name: "Igor Jesus", team: "Botafogo", subset: "Limited Edition", persons: ["Igor Jesus"] },
  { number: "LE2", name: "Cody Gakpo", team: "Liverpool", subset: "Limited Edition", persons: ["Cody Gakpo"] },
  { number: "LE3", name: "Dominik Szoboszlai", team: "Liverpool", subset: "Limited Edition", persons: ["Dominik Szoboszlai"] },
  { number: "LE4", name: "Florian Wirtz", team: "Liverpool", subset: "Limited Edition", persons: ["Florian Wirtz"] },
  { number: "LE5", name: "Jeremie Frimpong", team: "Liverpool", subset: "Limited Edition", persons: ["Jeremie Frimpong"] },
  { number: "LE6", name: "Milos Kerkez", team: "Liverpool", subset: "Limited Edition", persons: ["Milos Kerkez"] },
  { number: "LE7", name: "Mohamed Salah", team: "Liverpool", subset: "Limited Edition", persons: ["Mohamed Salah"] },
  { number: "LE8", name: "Ryan Gravenberch", team: "Liverpool", subset: "Limited Edition", persons: ["Ryan Gravenberch"] },
  { number: "LE9", name: "Virgil van Dijk", team: "Liverpool", subset: "Limited Edition", persons: ["Virgil van Dijk"] },
  { number: "LE10", name: "Achraf Hakimi", team: "Paris Saint-Germain", subset: "Limited Edition", persons: ["Achraf Hakimi"] },
  { number: "LE11", name: "Bradley Barcola", team: "Paris Saint-Germain", subset: "Limited Edition", persons: ["Bradley Barcola"] },
  { number: "LE12", name: "Désiré Doué", team: "Paris Saint-Germain", subset: "Limited Edition", persons: ["Désiré Doué"] },
  { number: "LE13", name: "Khvicha Kvaratskhelia", team: "Paris Saint-Germain", subset: "Limited Edition", persons: ["Khvicha Kvaratskhelia"] },
  { number: "LE14", name: "Ousmane Dembélé", team: "Paris Saint-Germain", subset: "Limited Edition", persons: ["Ousmane Dembélé"] },
  { number: "LE15", name: "Vitinha", team: "Paris Saint-Germain", subset: "Limited Edition", persons: ["Vitinha"] },
  { number: "LE16", name: "Edmond Tapsoba", team: "Bayer 04 Leverkusen", subset: "Limited Edition", persons: ["Edmond Tapsoba"] },
  { number: "LE17", name: "Patrik Schick", team: "Bayer 04 Leverkusen", subset: "Limited Edition", persons: ["Patrik Schick"] },
  { number: "LE18", name: "Hugo Larsson", team: "Eintracht Frankfurt", subset: "Limited Edition", persons: ["Hugo Larsson"] },
  { number: "LE19", name: "Jonathan Burkardt", team: "Eintracht Frankfurt", subset: "Limited Edition", persons: ["Jonathan Burkardt"] },
  { number: "LE20", name: "Denzel Dumfries", team: "FC Internazionale Milano", subset: "Limited Edition", persons: ["Denzel Dumfries"] },
  { number: "LE21", name: "Hakan Çalhanoğlu", team: "FC Internazionale Milano", subset: "Limited Edition", persons: ["Hakan Çalhanoğlu"] },
  { number: "LE22", name: "Lautaro Martínez", team: "FC Internazionale Milano", subset: "Limited Edition", persons: ["Lautaro Martínez"] },
  { number: "LE23", name: "Nicolò Barella", team: "FC Internazionale Milano", subset: "Limited Edition", persons: ["Nicolò Barella"] },
  { number: "LE24", name: "Rafael Leão", team: "AC Milan", subset: "Limited Edition", persons: ["Rafael Leão"] },
  { number: "LE25", name: "Cristiano Ronaldo", team: "Al-Nassr FC", subset: "Limited Edition", persons: ["Cristiano Ronaldo"] },
  { number: "LE26", name: "Julián Álvarez", team: "Atlético de Madrid", subset: "Limited Edition", persons: ["Julián Álvarez"] },
  { number: "LE27", name: "Lamine Yamal", team: "FC Barcelona", subset: "Limited Edition", persons: ["Lamine Yamal"] },
  { number: "LE28", name: "Pedri", team: "FC Barcelona", subset: "Limited Edition", persons: ["Pedri"] },
  { number: "LE29", name: "Raphinha", team: "FC Barcelona", subset: "Limited Edition", persons: ["Raphinha"] },
  { number: "LE30", name: "Robert Lewandowski", team: "FC Barcelona", subset: "Limited Edition", persons: ["Robert Lewandowski"] },
  { number: "LE31", name: "Jude Bellingham", team: "Real Madrid CF", subset: "Limited Edition", persons: ["Jude Bellingham"] },
  { number: "LE32", name: "Kylian Mbappé", team: "Real Madrid CF", subset: "Limited Edition", persons: ["Kylian Mbappé"] },
  { number: "LE33", name: "Vinicius Jr.", team: "Real Madrid CF", subset: "Limited Edition", persons: ["Vinicius Jr"] },
  { number: "LE34", name: "Lionel Messi", team: "Argentina", subset: "Limited Edition", persons: ["Lionel Messi"] },
  { number: "LE35", name: "Bukayo Saka", team: "England", subset: "Limited Edition", persons: ["Bukayo Saka"] },
  { number: "LE36", name: "Declan Rice", team: "England", subset: "Limited Edition", persons: ["Declan Rice"] },
  { number: "LE37", name: "Erling Haaland", team: "Norway", subset: "Limited Edition", persons: ["Erling Haaland"] },
  { number: "LE38", name: "Martin Ødegaard", team: "Norway", subset: "Limited Edition", persons: ["Martin Ødegaard"] },
];

async function main() {
  console.log(`Seeding: ${SET_NAME} (${ALL_CARDS.length} cards)`);

  const universeId = await builder.getOrCreateUniverse("Sports");
  const manufacturerId = await builder.getOrCreateManufacturer("Panini");
  const franchiseId = await builder.getOrCreateFranchise("Football (Soccer)", universeId);
  const brandId = await builder.getOrCreateBrand("Adrenalyn XL", manufacturerId);
  const seriesId = await builder.getOrCreateSeries("FIFA 365 2025", franchiseId, brandId);
  const set = await builder.getOrCreateSet({
    id: SET_ID,
    name: SET_NAME,
    seriesId,
    printedTotal: ALL_CARDS.length,
  });
  const basePrintingId = await builder.getOrCreatePrinting("Base");

  let created = 0;
  let skipped = 0;
  const t0 = Date.now();

  for (const [i, row] of ALL_CARDS.entries()) {
    const cardId = `${SET_ID}-${String(row.number).toLowerCase().replace(/[^a-z0-9]/g, "")}`;
    const existing = await prisma.card.findUnique({ where: { id: cardId } });
    if (existing) { skipped++; continue; }

    const personIds: string[] = [];
    if (row.persons) {
      for (const name of row.persons) personIds.push(await builder.getOrCreatePerson(name));
    }

    await prisma.card.create({
      data: {
        id: cardId,
        name: row.name,
        number: String(row.number),
        setId: set.id,
        supertype: row.subset ?? row.type ?? "Base",
        persons: personIds.length > 0 ? { connect: personIds.map((id) => ({ id })) } : undefined,
      },
    });

    created++;
    if ((i + 1) % 30 === 0) console.log(`  [${i + 1}/${ALL_CARDS.length}] created=${created}`);
  }

  console.log(`Done. Created ${created} cards, skipped ${skipped}. Set: ${SET_NAME} (${(Date.now() - t0) / 1000}s)`);
}

main()
  .catch((e) => { console.error(e); process.exitCode = 1; })
  .finally(async () => { await prisma.$disconnect(); });