-- Baseline hygiene per docs/adr/002-authentication-architecture.md §5: every table in the
-- exposed public schema gets RLS enabled with no policies (fail-closed) so the Supabase
-- Data API cannot read/write any of them even if a role is ever granted access. This does
-- NOT protect Prisma queries (which connect directly, bypassing PostgREST/RLS) — see the ADR.

ALTER TABLE "Artist" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Brand" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Card" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Certification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Character" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Contribution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DataSource" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Evidence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Franchise" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Identifier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Insight" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Instance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Location" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Manufacturer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MarketListing" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Media" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MediaAttachment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MediaVariant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MigrationRow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MigrationSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Pack" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Parallel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Person" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Population" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PossiblePull" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Printing" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductComponent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductRelationship" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectTarget" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Release" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Series" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Set" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Universe" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserMetrics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Variant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Wishlist" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_CardArtists" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_CardCharacters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_CardPersons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_CardTeams" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_PersonTeams" ENABLE ROW LEVEL SECURITY;
